### ISSUE TITLE
Ijin lapor

### ISSUE THREAD

**Issue by harispoppylatip** [MhankBarBar/whatsapp-bot#100]
Fitur FB.pokemon.stickergif tidak merespon klo stickergif sama fb cuman wait sedang di proses

Nanya : kalian juga sama kah

**Comment by aditalf** [comment]
aku lancar ko bg normal

**Comment by CE-10** [comment]
udah beli Key Belom ?

**Comment by harispoppylatip** [comment]
> udah beli Key Belom ?

Sudah

**Comment by alvinope** [comment]
> udah beli Key Belom ?

gmna cara nya??
