### ISSUE TITLE
100 Stars & 110 Forks GiveAway API-KEY

### ISSUE THREAD

**Issue by MFarelS** [MhankBarBar/whatsapp-bot#102]
Xixixi + Hilangkan Limitnya Mhank!!

**Comment by CE-10** [comment]
#2020_Give_Away_Api_Key :v

**Comment by alvinope** [comment]
> #2020_Give_Away_Api_Key :v

Fork Tembus 100 GiveAway API-KEY + Limitnya Hilangin:v ini apaan cuk ga ngerti

**Comment by rebahanelite** [comment]
padahal script rest apinya udah kesebar, tinggal deploy sendiri aja, udah unlimited api request, xixixi

**Comment by benirabbaby** [comment]
> padahal script rest apinya udah kesebar, tinggal deploy sendiri aja, udah unlimited api request, xixixi

bagi, w ga punya :v

**Comment by AthallahDzaki** [comment]
Password Rest APInya apa?

**Comment by MhankBarBar** [comment]
Seenggaknya hargain orang yang bikin rest apinya gan, close.
