### ISSUE TITLE
ytmp4 error

### ISSUE THREAD

**Issue by lokublah** [MhankBarBar/whatsapp-bot#108]
"error mungkin disebbkn oleh sistem"Sama lama Lama botny ga respon gitu tpi di cmdny msuk

**Comment by CE-10** [comment]
coba pencet Ctrl+C terus npm start

**Comment by lokublah** [comment]
> coba pencet Ctrl+C terus npm start

iy w gitu trus rmlih,lm lm jg jengkel mesti gtu trus

**Comment by MhankBarBar** [comment]
![Screenshot_2020-11-04-13-11-30-64](https://user-images.githubusercontent.com/55822959/98075618-49b27e80-1e9f-11eb-9806-bbf490e430b3.jpg)

**Comment by MhankBarBar** [comment]
Di gue gada error Tapi banyak bet yang ngeluh ini error itu error

**Comment by ItzTobz** [comment]
Yang error coba ganti aja requests get jadi axios

**Comment by kikiixyz** [comment]
apikey limit mhank

**Comment by muhammadzakizn07** [comment]
sama w juga error

**Comment by lxndr-rl** [comment]
You can use ytdl-core instead
