### ISSUE TITLE
cara mengedit nomor whatsapp saya di bot

### ISSUE THREAD

**Issue by NaldoMota1** [MhankBarBar/whatsapp-bot#113]

**Comment by Cokjanco** [comment]
> _No description provided._

Edit file msgHndlr.js, di line 67 ganti ke nomer wa kamu 

ex: 62894372843 awal nomer harus 62

**Comment by NaldoMota1** [comment]
![Capturar](https://user-images.githubusercontent.com/71650872/98365189-cb75e980-2010-11eb-82ec-3d0a39c42b6a.PNG)

apa kesalahan ini?

**Comment by MhankBarBar** [comment]
install bukan instale, kalo ngetik melek gan wkwk

**Comment by CE-10** [comment]
> 
> 
> ![Capturar](https://user-images.githubusercontent.com/71650872/98365189-cb75e980-2010-11eb-82ec-3d0a39c42b6a.PNG)
> 
> apa kesalahan ini?

npm ~instale~ gify-cli -g
