### ISSUE TITLE
Whatsapp bot 

### ISSUE THREAD

**Issue by ASLKiRa** [MhankBarBar/whatsapp-bot#123]

**Comment by SlavyanDesu** [comment]
Huh?

**Comment by XaRuToX** [comment]
> Huh?

Iae mano, vc tem WhatsApp

Se tiver me manda

E diz tbm como q faz pra colocar ft no perfil, vlw. 

@![images.jpeg](https://user-images.githubusercontent.com/63880084/103159129-574ffa80-47a4-11eb-9b15-d98fa02debc3.jpeg)

**Comment by SlavyanDesu** [comment]
> > Huh?
> 
> Iae mano, vc tem WhatsApp
> 
> Se tiver me manda
> 
> E diz tbm como q faz pra colocar ft no perfil, vlw.
> 
> @SlavyanDesu
> 
> ![images.jpeg](https://user-images.githubusercontent.com/63880084/103159129-574ffa80-47a4-11eb-9b15-d98fa02debc3.jpeg)

```
Hey bro, you have WhatsApp

If you have send me

And says tbm as q does to put ft in the profile, vlw.
```
Translated with Google.
What do you need though?

**Comment by ASLKiRa** [comment]
@SlavyanDesu 

Well man, I’m trying to make a whatsapp bot, but by termux, I don’t have a computer to do it on Linux, it’s really hard, I found a method that’s really cool to do, however, it only works on Linux, for termux it’s really difficult, if you can give any tips I appreciate

**Comment by SlavyanDesu** [comment]
> @SlavyanDesu
> 
> Well man, I’m trying to make a whatsapp bot, but by termux, I don’t have a computer to do it on Linux, it’s really hard, I found a method that’s really cool to do, however, it only works on Linux, for termux it’s really difficult, if you can give any tips I appreciate

Check [this repo](https://github.com/fdciabdul/termux-whatsapp-bot)

**Comment by MhankBarBar** [comment]
Salah server anjay
