### ISSUE TITLE
Doujin Downloader [ASK]

### ISSUE THREAD

**Issue by SlavyanDesu** [MhankBarBar/whatsapp-bot#124]
Mhank, buat doujin downloader module-nya ada pengganti yang lain gak? Pernah tuh liat ada bot sebelah yang work doujin downloader-nya, ngirim via file .pdf juga

**Comment by MhankBarBar** [comment]
Gue juga mau buat apinya sih, tapi ga blom terus wkwk, recommended pake module nhentai [ python ]

**Comment by SlavyanDesu** [comment]
Buseet mau di bikin API-nya, gas kan gw tunggu otw order API key kalau udah jadi aowkwokwok

**Comment by MhankBarBar** [comment]
[nih cek wkwk](https://mhankbarbar.herokuapp.com/dok/nhentai)

**Comment by TentacleSama4254** [comment]
> [nih cek wkwk](https://mhankbarbar.herokuapp.com/dok/nhentai)

how to use?

**Comment by SlavyanDesu** [comment]
> > [nih cek wkwk](https://mhankbarbar.herokuapp.com/dok/nhentai)
> 
> how to use?

By purchasing his API key access.
