### ISSUE TITLE
ytmp4 / ytmp3 error.

### ISSUE THREAD

**Issue by gabrielwsy** [MhankBarBar/whatsapp-bot#130]
I have a problem, not downloading the file ytmp3 and ytmp4, how can I solve? 
![image](https://user-images.githubusercontent.com/40281950/99688533-af3c6880-2a64-11eb-8b1a-76d0f53a163b.png)

**Comment by MhankBarBar** [comment]
![Screenshot_2020-11-19-22-53-59-77](https://user-images.githubusercontent.com/55822959/99689932-24865880-2aba-11eb-9b8b-6047e5ceaa5f.jpg)
Error???

**Comment by gabrielwsy** [comment]
> ![Screenshot_2020-11-19-22-53-59-77](https://user-images.githubusercontent.com/55822959/99689932-24865880-2aba-11eb-9b8b-6047e5ceaa5f.jpg)
> Error???

Hi, I apologize, I just published the post on the wrong project, sorry for my lack of attention ...

**Comment by gabrielwsy** [comment]
I have another question, how do I get an api on the site? sorry, i'm new here.
![image](https://user-images.githubusercontent.com/40281950/99694293-09402c80-2a6b-11eb-8fdf-b2abdd72a6f8.png)

**Comment by MhankBarBar** [comment]
[chat me on whatsapp](https://wa.me/6285892766102)

**Comment by MhankBarBar** [comment]
Close
