### ISSUE TITLE
Fitur Error Ditemukan Lagi

### ISSUE THREAD

**Issue by MFarelSyahtiawan** [MhankBarBar/whatsapp-bot#14]
Yaitu fitur ban 

Padahal udah di ban, tapi tetep kaga ke ban

**Comment by MFarelSyahtiawan** [comment]
> Yaitu fitur ban
> 
> Padahal udah di ban, tapi tetep kaga ke ban

Ada tulisannya dih "Target Telah Di Banned" Tapi kok masih bisa pake fiturnya

**Comment by TRENWAR** [comment]
Itu karena.....eeeee..

Pada tanggal Rab, 23 Sep 2020 21.13, MFarelSyahtiawan <
notifications@github.com> menulis:
