### ISSUE TITLE
Semua Pengguna Bot Milik @MhankBarBar Error

### ISSUE THREAD

**Issue by MFarelSyahtiawan** [MhankBarBar/whatsapp-bot#15]
![IMG_20200924_085300](https://user-images.githubusercontent.com/58540890/94094021-bcfcb580-fe48-11ea-83e3-63097f48955c.jpg)
Itu Kenapa Ya Bang!!!

**Comment by MhankBarBar** [comment]
[cek disini](https://github.com/open-wa/wa-automate-nodejs/issues/850)

**Comment by MFarelSyahtiawan** [comment]
> [cek disini](https://github.com/open-wa/wa-automate-nodejs/issues/850)

Bingung bang! 
Itu nanti textnya disalin trus di paste ke?

**Comment by shansekai** [comment]
> > [cek disini](https://github.com/open-wa/wa-automate-nodejs/issues/850)
> 
> Bingung bang!
> Itu nanti textnya disalin trus di paste ke?

Copy semua text ini : [https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js](https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js) 
Terus masuk ke folder : @open-wa => wa-automate => dist => lib => wapi.js  dan replace yang text lu copy tadi.

**Comment by MFarelSyahtiawan** [comment]
> > > [cek disini](https://github.com/open-wa/wa-automate-nodejs/issues/850)
> > 
> > 
> > Bingung bang!
> > Itu nanti textnya disalin trus di paste ke?
> 
> Copy semua text di dlm link ini : https://raw.githubusercontent.com/open-wa/wa-automate-nodejs/f4cc51423aa367ad3c7b735a799d6f7d6ab05051/src/lib/wapi.js
> Terus masuk ke folder : `@open-wa => wa-automate => dist => lib => wapi.js` dan replace yang text lu copy tadi.

Ok Tengs Bang!
