### ISSUE TITLE
HOW TO START?

### ISSUE THREAD

**Issue by ben-dev2609** [MhankBarBar/whatsapp-bot#16]
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm WARN eslint-plugin-import@2.22.0 requires a peer of eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@6.0.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN User No description
npm WARN User No repository field.
npm WARN User No README data
npm WARN User No license field.

audited 427 packages in 18.373s

50 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

C:\Users\User>npm start

┌───────────────────────────────────────────────────────────┐
│                  npm update check failed                  │
│            Try running with sudo or get access            │
│           to the local update config store via            │
│ sudo chown -R $USER:$(id -gn $USER) C:\Users\User\.config │
└───────────────────────────────────────────────────────────┘
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\User\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-09-25T03_18_06_659Z-debug.log

C:\Users\User>npm i
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm WARN eslint-plugin-import@2.22.0 requires a peer of eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@6.0.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN User No description
npm WARN User No repository field.
npm WARN User No README data
npm WARN User No license field.

audited 427 packages in 22.678s

50 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by RaphielHS** [comment]
Have you cloned the repository?

**Comment by RaphielHS** [comment]
If you cloned the repository, change directory and use **npm start**

**Comment by RaphielHS** [comment]
And i found out the error, the directory that you use **npm i** and **npm start** is not the folder / directory where's the code is, (package.json). So cd (change directory) to the bot code file.

**Comment by ben-dev2609** [comment]
im done clone and what is cd?

**Comment by RaphielHS** [comment]
cd stands for "change directory"

**Comment by RaphielHS** [comment]
You can't run the code if you're not in the code file, that's the place where you're got those errors

**Comment by ben-dev2609** [comment]
im not understand

**Comment by RaphielHS** [comment]
If your command prompt is not in the same directory (file location) to the code, it will not work

**Comment by ben-dev2609** [comment]
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm WARN eslint-plugin-import@2.22.0 requires a peer of eslint@^2 || ^3 || ^4 || ^5 || ^6 || ^7.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-node@6.0.1 requires a peer of eslint@>=3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN User No description
npm WARN User No repository field.
npm WARN User No README data
npm WARN User No license field.

audited 427 packages in 21.25s

50 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities




this?

**Comment by RaphielHS** [comment]
Wait I'll show you how to change directories

**Comment by RaphielHS** [comment]
Type this to your command prompt
C:/Users/User/Desktop/whatsapp-bot-master

Then type
npm i
npm start

**Comment by ben-dev2609** [comment]
'C:/Users/User/Desktop/whatsapp-bot-master' is not recognized as an internal or external command,
operable program or batch file.

**Comment by ben-dev2609** [comment]
btw sorry im new hehe

**Comment by RaphielHS** [comment]
have you cloned the repo?
if not, download as .zip and extract to your desktop
link: https://github.com/MhankBarBar/whatsapp-bot/archive/master.zip

**Comment by ben-dev2609** [comment]
Im done to download ,what more?

**Comment by RaphielHS** [comment]
Extract the .zip file to your desktop
and open command prompt and type
cd C:/Users/User/Desktop/whatsapp-bot-master

**Comment by ben-dev2609** [comment]
what more?

**Comment by RaphielHS** [comment]
then type
**npm install**
then wait, then type
**npm start**

**Comment by ben-dev2609** [comment]
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\User\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\User\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\User\AppData\Roaming\npm-cache\_logs\2020-09-25T03_51_12_771Z-debug.log

**Comment by RaphielHS** [comment]
have you cd-ed it?
(cd C:/Users/User/Desktop/whatsapp-bot-master)

**Comment by ben-dev2609** [comment]
yea

**Comment by ben-dev2609** [comment]
i do it at nodejs right?

**Comment by RaphielHS** [comment]
it should say C:/Users/User/Desktop/whatsapp-bot-master on the side of your command promt

**Comment by RaphielHS** [comment]
this should be [usefull for you](https://www.digitalcitizen.life/command-prompt-how-use-basic-commands)

**Comment by ben-dev2609** [comment]
The system cannot find the drive specified.

**Comment by RaphielHS** [comment]
I don't know then, try watching a tutorial on how to setup npm or change directories or npm install and npm start
