### ISSUE TITLE
Command !nulis tapi gada tulisannya??

### ISSUE THREAD

**Issue by MhankBarBar** [MhankBarBar/whatsapp-bot#17]
Pertama

Install [`imagemagick`](https://imagemagick.org/script/download.php)

Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke <b>C:\Windows\Fonts</b> kalo udah download > install > move. Langsung rasakan sensasinya:v

**Comment by MFarelSyahtiawan** [comment]
bikin tutornya bang!

ane bingung

**Comment by MhankBarBar** [comment]
Bingung gimana? Cuma download > install > download lagi > move > done

**Comment by MFarelSyahtiawan** [comment]
kan udah download tuh imagemick nya, nah abis install, buka cmd ketik apa?

**Comment by MFarelSyahtiawan** [comment]
ane udah install masih kaga ada text nya bang!!!!!!!

**Comment by MhankBarBar** [comment]
Serius??

Ada loh seharusnya kalo dah diinstall

**Comment by restugbk** [comment]
gabisa

**Comment by MhankBarBar** [comment]
Bisa njirr, gabisa² terus

**Comment by mcpr259** [comment]
Imge magic nya gabisa di download bang 404 not foud

**Comment by MFarelSyahtiawan** [comment]
> Pertama
> 
> Install [`imagemagick`](https://imagemagick.org/script/download.php)
> 
> Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v

Alhamdulillah Work Bang

Work di Win7

Win10 kaga work:v

**Comment by benirabbny** [comment]
> > Pertama
> > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> 
> Alhamdulillah Work Bang
> 
> Work di Win7
> 
> Win10 kaga work:v

di rdp windows server kaga bisa

**Comment by aidilaryanto** [comment]
Kalau linux gimana?

**Comment by Sytxx** [comment]
> Kalau linux gimana?

iya betul di ubuntu 18.04 bsia bg ?

**Comment by MhankBarBar** [comment]
Saya ga install Linux sama ubuntu jadi kurang tau wkwk

**Comment by mcpr259** [comment]
a

> Saya ga install Linux sama ubuntu jadi kurang tau wkwk

abang pake rdp ?

**Comment by MhankBarBar** [comment]
Iya rdp

**Comment by benirabbny** [comment]
> Iya rdp

lah, di rdp work ?
kok saya ga work ya

**Comment by mcpr259** [comment]
> Iya rdp
windows 10?

**Comment by benirabbny** [comment]
Rdp windows server

**Comment by benirabbny** [comment]
![image](https://user-images.githubusercontent.com/68042984/95033483-aa0ba000-06e8-11eb-9038-5c88c8bf16a6.png)
kok kaga jawabnya kaga sesuai ya

**Comment by Cahyo224** [comment]
> > Pertama
> > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> 
> Alhamdulillah Work Bang
> 
> Work di Win7
> 
> Win10 kaga work:v

Win 10 Ane work

**Comment by MhankBarBar** [comment]
> ![image](https://user-images.githubusercontent.com/68042984/95033483-aa0ba000-06e8-11eb-9038-5c88c8bf16a6.png)
> kok kaga jawabnya kaga sesuai ya

Dah dibilang install imagemagick dulu

**Comment by benirabbny** [comment]
> > ![image](https://user-images.githubusercontent.com/68042984/95033483-aa0ba000-06e8-11eb-9038-5c88c8bf16a6.png)
> > kok kaga jawabnya kaga sesuai ya
> 
> Dah dibilang install imagemagick dulu

udah bapack

**Comment by MhankBarBar** [comment]
Klo dah di install gabakalan resultnya kek gitu

**Comment by benirabbny** [comment]
> Klo dah di install gabakalan resultnya kek gitu

![image](https://user-images.githubusercontent.com/68042984/95045823-05e82000-070d-11eb-9735-19d843a23cd8.png)
apakah aku salah install ?

**Comment by MhankBarBar** [comment]
![IMG-20201005-WA0161](https://user-images.githubusercontent.com/55822959/95046099-a0486380-070d-11eb-88a0-781e99d5049b.jpg)

Bagian itu di centang? Ga kan?

**Comment by Cahyo224** [comment]
> ![IMG-20201005-WA0161](https://user-images.githubusercontent.com/55822959/95046099-a0486380-070d-11eb-88a0-781e99d5049b.jpg)
> 
> Bagian itu di centang? Ga kan?
> 
> Bagian itu tuh di centang kalo ga ya gabakalan bisa di run perintah convert nya

@benirabbny itu coba lu install ulang lagi

**Comment by benirabbny** [comment]
> > ![IMG-20201005-WA0161](https://user-images.githubusercontent.com/55822959/95046099-a0486380-070d-11eb-88a0-781e99d5049b.jpg)
> > Bagian itu di centang? Ga kan?
> > Bagian itu tuh di centang kalo ga ya gabakalan bisa di run perintah convert nya
> 
> @benirabbny itu coba lu install ulang lagi



> ![IMG-20201005-WA0161](https://user-images.githubusercontent.com/55822959/95046099-a0486380-070d-11eb-88a0-781e99d5049b.jpg)
> 
> Bagian itu di centang? Ga kan?
> 
> Bagian itu tuh di centang kalo ga ya gabakalan bisa di run perintah convert nya

uda semua, ummm

**Comment by MhankBarBar** [comment]
Semua orang disini selesai masalahnya kalo itu dah di centang njirr

**Comment by benirabbny** [comment]
> Semua orang disini selesai masalahnya kalo itu dah di centang njirr

kecuali saya :|

**Comment by acanva** [comment]
> Pertama
> 
> Install [`imagemagick`](https://imagemagick.org/script/download.php)
> 
> Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v

Udah bisa bang cuma fontnya bukan indie flower
udahikutin step per step tapi fontnya bukan indie flower :)

**Comment by bl4nk0n** [comment]
untuk pengguna linux (vps)  bisa gunakan "sudo apt-get install ttf-mscorefonts-installer" setelah itu fc-cache -fv.
jangan lupa install imagemagick.
:+1:

**Comment by mcpr259** [comment]
> > Pertama
> > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> 
> Udah bisa bang cuma fontnya bukan indie flower
> udahikutin step per step tapi fontnya bukan indie flower :)

sama bang

**Comment by Cahyo224** [comment]
> > > Pertama
> > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > 
> > 
> > Udah bisa bang cuma fontnya bukan indie flower
> > udahikutin step per step tapi fontnya bukan indie flower :)
> 
> sama bang

weh kok bisa gitu ya bukan Font Indie-Flower

**Comment by acanva** [comment]
> > > > Pertama
> > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > 
> > > 
> > > Udah bisa bang cuma fontnya bukan indie flower
> > > udahikutin step per step tapi fontnya bukan indie flower :)
> > 
> > 
> > sama bang
> 
> weh kok bisa gitu ya bukan Font Indie-Flower

gatau padahal udah di pindah sama di install juga kok

**Comment by acanva** [comment]
> > > Pertama
> > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > 
> > 
> > Udah bisa bang cuma fontnya bukan indie flower
> > udahikutin step per step tapi fontnya bukan indie flower :)
> 
> sama bang

senasib kita wkwkwkw

**Comment by bl4nk0n** [comment]
> > > > Pertama
> > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > 
> > > 
> > > Udah bisa bang cuma fontnya bukan indie flower
> > > udahikutin step per step tapi fontnya bukan indie flower :)
> > 
> > 
> > sama bang
> 
> senasib kita wkwkwkw

cek lagi file di "msgHndlr" ctrl+f - !nulis
ganti format font nya ke Indie-Flower ( dikasih - )
akan work jika font sudah di install di dir yang benar :100:

**Comment by acanva** [comment]
> > > > > Pertama
> > > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > > 
> > > > 
> > > > Udah bisa bang cuma fontnya bukan indie flower
> > > > udahikutin step per step tapi fontnya bukan indie flower :)
> > > 
> > > 
> > > sama bang
> > 
> > 
> > senasib kita wkwkwkw
> 
> cek lagi file di "msgHndlr" ctrl+f - !nulis
> ganti format font nya ke Indie-Flower ( dikasih - )
> akan work jika font sudah di install di dir yang benar 💯

masih sama bang, padahal udah di install di dir yang bener kok :(

**Comment by benirabbny** [comment]
> > > > > > Pertama
> > > > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > > > 
> > > > > 
> > > > > Udah bisa bang cuma fontnya bukan indie flower
> > > > > udahikutin step per step tapi fontnya bukan indie flower :)
> > > > 
> > > > 
> > > > sama bang
> > > 
> > > 
> > > senasib kita wkwkwkw
> > 
> > 
> > cek lagi file di "msgHndlr" ctrl+f - !nulis
> > ganti format font nya ke Indie-Flower ( dikasih - )
> > akan work jika font sudah di install di dir yang benar 💯
> 
> masih sama bang, padahal udah di install di dir yang bener kok :(

pake windows apa ?

**Comment by acanva** [comment]
> > > > > > > Pertama
> > > > > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > > > > 
> > > > > > 
> > > > > > Udah bisa bang cuma fontnya bukan indie flower
> > > > > > udahikutin step per step tapi fontnya bukan indie flower :)
> > > > > 
> > > > > 
> > > > > sama bang
> > > > 
> > > > 
> > > > senasib kita wkwkwkw
> > > 
> > > 
> > > cek lagi file di "msgHndlr" ctrl+f - !nulis
> > > ganti format font nya ke Indie-Flower ( dikasih - )
> > > akan work jika font sudah di install di dir yang benar 💯
> > 
> > 
> > masih sama bang, padahal udah di install di dir yang bener kok :(
> 
> pake windows apa ?

windows 10 bang

**Comment by Cahyo224** [comment]
> > > > > > > > Pertama
> > > > > > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > > > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > > > > > 
> > > > > > > 
> > > > > > > Udah bisa bang cuma fontnya bukan indie flower
> > > > > > > udahikutin step per step tapi fontnya bukan indie flower :)
> > > > > > 
> > > > > > 
> > > > > > sama bang
> > > > > 
> > > > > 
> > > > > senasib kita wkwkwkw
> > > > 
> > > > 
> > > > cek lagi file di "msgHndlr" ctrl+f - !nulis
> > > > ganti format font nya ke Indie-Flower ( dikasih - )
> > > > akan work jika font sudah di install di dir yang benar 💯
> > > 
> > > 
> > > masih sama bang, padahal udah di install di dir yang bener kok :(
> > 
> > 
> > pake windows apa ?
> 
> windows 10 bang

gua windows 10 bisa lo

**Comment by acanva** [comment]
> > > > > > > > > Pertama
> > > > > > > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > > > > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Udah bisa bang cuma fontnya bukan indie flower
> > > > > > > > udahikutin step per step tapi fontnya bukan indie flower :)
> > > > > > > 
> > > > > > > 
> > > > > > > sama bang
> > > > > > 
> > > > > > 
> > > > > > senasib kita wkwkwkw
> > > > > 
> > > > > 
> > > > > cek lagi file di "msgHndlr" ctrl+f - !nulis
> > > > > ganti format font nya ke Indie-Flower ( dikasih - )
> > > > > akan work jika font sudah di install di dir yang benar 💯
> > > > 
> > > > 
> > > > masih sama bang, padahal udah di install di dir yang bener kok :(
> > > 
> > > 
> > > pake windows apa ?
> > 
> > 
> > windows 10 bang
> 
> gua windows 10 bisa lo

laaa beda sendiri 😢

**Comment by MhankBarBar** [comment]
Kurang iman mungkin🤭

**Comment by bagusdwip** [comment]
Help udah install imagemagick sama font gabisa :(

**Comment by MSI0072** [comment]
> untuk pengguna linux (vps) bisa gunakan "sudo apt-get install ttf-mscorefonts-installer" setelah itu fc-cache -fv.
> jangan lupa install imagemagick.
> +1

cara install imagemagick di linux gimana ya

**Comment by MSI0072** [comment]
> untuk pengguna linux (vps) bisa gunakan "sudo apt-get install ttf-mscorefonts-installer" setelah itu fc-cache -fv.
> jangan lupa install imagemagick.
> +1

udah install semua , tapi ga keluar tulisannya

**Comment by MSI0072** [comment]
> Pertama
> 
> Install [`imagemagick`](https://imagemagick.org/script/download.php)
> 
> Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v

![image](https://user-images.githubusercontent.com/63404067/95678038-ec0a7980-0bf3-11eb-8648-4aaeb3e95eac.png)

Udah install semua nya tapi ga jalan

![image](https://user-images.githubusercontent.com/63404067/95678052-05132a80-0bf4-11eb-8685-3d48d90d58c3.png)

**Comment by ArugaZ** [comment]
> > > > Pertama
> > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > 
> > > 
> > > Udah bisa bang cuma fontnya bukan indie flower
> > > udahikutin step per step tapi fontnya bukan indie flower :)
> > 
> > 
> > sama bang
> 
> weh kok bisa gitu ya bukan Font Indie-Flower

pas di cek convert -list font gada Indie-Flower

**Comment by Anang11042000** [comment]
Klo pke termux bisa gak?

**Comment by acanva** [comment]
> > Pertama
> > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> 
> ![image](https://user-images.githubusercontent.com/63404067/95678038-ec0a7980-0bf3-11eb-8648-4aaeb3e95eac.png)
> 
> Udah install semua nya tapi ga jalan
> 
> ![image](https://user-images.githubusercontent.com/63404067/95678052-05132a80-0bf4-11eb-8685-3d48d90d58c3.png)

pas install image magic nya di ceklis ga semua ga?

**Comment by ArugaZ** [comment]
> > Pertama
> > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> 
> ![image](https://user-images.githubusercontent.com/63404067/95678038-ec0a7980-0bf3-11eb-8648-4aaeb3e95eac.png)
> 
> Udah install semua nya tapi ga jalan
> 
> ![image](https://user-images.githubusercontent.com/63404067/95678052-05132a80-0bf4-11eb-8685-3d48d90d58c3.png)

coba buka cmd, lalu ketik : conver -list font, liat font Indie-Flower udah ada atau blm

**Comment by acanva** [comment]
> > > > > Pertama
> > > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > > 
> > > > 
> > > > Udah bisa bang cuma fontnya bukan indie flower
> > > > udahikutin step per step tapi fontnya bukan indie flower :)
> > > 
> > > 
> > > sama bang
> > 
> > 
> > weh kok bisa gitu ya bukan Font Indie-Flower
> 
> pas di cek convert -list font gada Indie-Flower

udah cek ternyata gaada fontnya, kok bisa ya ? padahal udah di download

**Comment by lawliet5** [comment]
Sama gw juga gk da pas saya cek di cmd.

**Comment by MSI0072** [comment]
> > > Pertama
> > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/63404067/95678038-ec0a7980-0bf3-11eb-8648-4aaeb3e95eac.png)
> > Udah install semua nya tapi ga jalan
> > ![image](https://user-images.githubusercontent.com/63404067/95678052-05132a80-0bf4-11eb-8685-3d48d90d58c3.png)
> 
> coba buka cmd, lalu ketik : convert -list font, liat font Indie-Flower udah ada atau blm

Udah muncul min, cara ganti font gimana ya

![Screenshot_20201013-050042_WhatsApp](https://user-images.githubusercontent.com/63404067/95794158-74cb0780-0d11-11eb-9e76-88b077d7d9d0.jpg)

**Comment by MSI0072** [comment]
> > > Pertama
> > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/63404067/95678038-ec0a7980-0bf3-11eb-8648-4aaeb3e95eac.png)
> > Udah install semua nya tapi ga jalan
> > ![image](https://user-images.githubusercontent.com/63404067/95678052-05132a80-0bf4-11eb-8685-3d48d90d58c3.png)
> 
> coba buka cmd, lalu ketik : convert -list font, liat font Indie-Flower udah ada atau blm

![image](https://user-images.githubusercontent.com/63404067/95803228-c8494f80-0d29-11eb-840a-30655f2ca93b.png)
udah saya install cuma di cek lewat CMD ga ada, gimana ya

**Comment by akumund** [comment]
> > > > > > Pertama
> > > > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > > > 
> > > > > 
> > > > > Udah bisa bang cuma fontnya bukan indie flower
> > > > > udahikutin step per step tapi fontnya bukan indie flower :)
> > > > 
> > > > 
> > > > sama bang
> > > 
> > > 
> > > weh kok bisa gitu ya bukan Font Indie-Flower
> > 
> > 
> > pas di cek convert -list font gada Indie-Flower
> 
> udah cek ternyata gaada fontnya, kok bisa ya ? padahal udah di download

sama
wkowkwok

**Comment by bdrsmsdn** [comment]
> > > > > > > Pertama
> > > > > > > Install [`imagemagick`](https://imagemagick.org/script/download.php)
> > > > > > > Kalo udah install Jan lupa download font [`Indie-Flower`](https://fonts.google.com/specimen/Indie+Flower) terus di move ke C:\Windows\Fonts kalo udah download > install > move. Langsung rasakan sensasinya:v
> > > > > > 
> > > > > > 
> > > > > > Udah bisa bang cuma fontnya bukan indie flower
> > > > > > udahikutin step per step tapi fontnya bukan indie flower :)
> > > > > 
> > > > > 
> > > > > sama bang
> > > > 
> > > > 
> > > > weh kok bisa gitu ya bukan Font Indie-Flower
> > > 
> > > 
> > > pas di cek convert -list font gada Indie-Flower
> > 
> > 
> > udah cek ternyata gaada fontnya, kok bisa ya ? padahal udah di download
> 
> sama
> wkowkwok

udah bner belum bang? punya gue fontnya malah bukan indie flower
