### ISSUE TITLE
ad yg tau knp gini?

### ISSUE THREAD

**Issue by rzr29** [MhankBarBar/whatsapp-bot#172]
![Screenshot_2021-01-01-09-27-58-33_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/76828800/103432578-e5e4d180-4c13-11eb-98b5-e56f733693c0.jpg)

**Comment by Pokoke-01** [comment]
Bot ini tidak support untuk dijalankan di Termux
