### ISSUE TITLE
How does !ytmp3 and !ytmp4 work?

### ISSUE THREAD

**Issue by Sordinni** [MhankBarBar/whatsapp-bot#175]

**Comment by lxndr-rl** [comment]
You can use ytdl module ^-^

**Comment by AlissoNNunes1** [comment]
whats is the apikey?

**Comment by lxndr-rl** [comment]
ApiKey for use https://mhankbarbars.herokuapp.com/api

In the case of yt you can use ytdl-core instead

**Comment by MhankBarBar** [comment]
[check here](https://mhankbarbar.tech/api)
