### ISSUE TITLE
Ask Me

### ISSUE THREAD

**Issue by restugbk** [MhankBarBar/whatsapp-bot#18]
Kenapa nih errornya gan?
https://prnt.sc/uo11bc

**Comment by MhankBarBar** [comment]
Itu pas ada yang send perintah <b>!join</b>?

**Comment by restugbk** [comment]
iyaa gan

**Comment by MhankBarBar** [comment]
Sampe sekarang masih begitu kah? Apa udah ngk?

**Comment by restugbk** [comment]
udah ngga, trus sama nulis itu gmna yaa caranya? kok teksnya kosong?

**Comment by MhankBarBar** [comment]
[nih!](https://github.com/MhankBarBar/whatsapp-bot/issues/17)

**Comment by restugbk** [comment]
udh ikutin itu, tapi masih gada teksnya??

**Comment by MhankBarBar** [comment]
Pas install imagemagick pasti langsung next² kan

**Comment by restugbk** [comment]
iyaa, masih gabisa

**Comment by MhankBarBar** [comment]
Dah fix? Close
