### ISSUE TITLE
What's the ApiKey?And the Apikey's site doesn't work,please update

### ISSUE THREAD

**Issue by AlissoNNunes1** [MhankBarBar/whatsapp-bot#185]
What's the ApiKey?And the Apikey's site doesn't work,please update

**Comment by lxndr-rl** [comment]
Apparently the MhankBarBar api is not available, you can replace the api by creating your own api or make the queries directly from the bot

**Comment by AlissoNNunes1** [comment]
thanks for the help

**Comment by MhankBarBar** [comment]
> What's the ApiKey?And the Apikey's site doesn't work,please update

web api has changed domains [click here for check](https://mhankbarbar.tech/api)

**Comment by MhankBarBar** [comment]
Changed domain again to [this](https://antei.codes)

> this api doesnt work , this is just for now or whats happen? thanks for all
