### ISSUE TITLE
Failed to launch browser process

### ISSUE THREAD

**Issue by acanva** [MhankBarBar/whatsapp-bot#19]
Ini kenapa ya??? Udah npm i pas npm start keluarnya tulisan error failed to launch browser process.
Mohon bantuannya, terima kasih :)
![image](https://user-images.githubusercontent.com/71750722/94357525-b75ed400-00c3-11eb-9e93-3586d5d660d4.png)

**Comment by MhankBarBar** [comment]
Remove dir/folder .node-persist

**Comment by acanva** [comment]
> dir/folder .node-persist

masih gak bisa bang

**Comment by restugbk** [comment]
itu dir browsernya setting dulu sesuai pcnya

**Comment by acanva** [comment]
> itu dir browsernya setting dulu sesuai pcnya

gimana caranya ya bang???

**Comment by shansekai** [comment]
> > itu dir browsernya setting dulu sesuai pcnya
> 
> gimana caranya ya bang???

![20200927_205709](https://user-images.githubusercontent.com/34540627/94366686-0f1d2f80-0104-11eb-98db-9780773e9f54.png)
Chromenya tarus disini coba

**Comment by acanva** [comment]
> > > itu dir browsernya setting dulu sesuai pcnya
> > 
> > 
> > gimana caranya ya bang???
> 
> ![20200927_205709](https://user-images.githubusercontent.com/34540627/94366686-0f1d2f80-0104-11eb-98db-9780773e9f54.png)
> Chromenya taruh disini coba

sudah bisa, makasih banyak bang
