### ISSUE TITLE
IG Downloader

### ISSUE THREAD

**Issue by dzakijo1** [MhankBarBar/whatsapp-bot#2]
Ig downloader error gan:( ane make rdp how to fix it? 
![image](https://user-images.githubusercontent.com/47619660/91691030-244c8000-eb91-11ea-8960-f7ac9890e83a.png)

**Comment by MhankBarBar** [comment]
Api nya yang error gan:v

**Comment by dzakijo1** [comment]
wqwqwq help bruh :v yang sebelumnya enak ig downloader sama fb downloader
