### ISSUE TITLE
sendfilefromUrl to download videos

### ISSUE THREAD

**Issue by aymenitc** [MhankBarBar/whatsapp-bot#215]
Hi, when I use sendfilefromUrl function to download videos from youtube or tiktok I get BIN compressed file. The video inside the BIN file. Any idea how to fix this to send video to whatsapp?

**Comment by Wizard12347** [comment]
Quero n porra

Em Qui, 4 de mar de 2021 6:51 PM, aymenitc <notifications@github.com>
escreveu:

**Comment by aymenitc** [comment]
now is working after open-wa patch
