### ISSUE TITLE
Command !nulis bisa, tapi fontnya ngawur

### ISSUE THREAD

**Issue by Bintang73** [MhankBarBar/whatsapp-bot#22]
Mhank, mau tanya, command nulisnya sih bisa, ngirim gambar dengan teks, tapi fontnya ngawur dan berantakan

![Screenshot_2020-09-29-20-05-24-15](https://user-images.githubusercontent.com/42708989/94563209-8ed80500-0290-11eb-930d-51cbb16edc16.jpg)

**Comment by MhankBarBar** [comment]
![Screenshot_2020-09-29-20-18-38-70](https://user-images.githubusercontent.com/55822959/94563487-fc843100-0290-11eb-8776-49ecb182a48e.jpg)

Ngawur??

**Comment by MhankBarBar** [comment]
Close!

**Comment by Bintang73** [comment]
Iya Font nya bukan Indie Flower

**Comment by Bintang73** [comment]
Font indie flower tidak bisa terbaca

**Comment by jsmnkk** [comment]
Gini bang
Di sambung gitu pake karakter 👉 - di tengah nya
Contoh:
Indie-Flower
