### ISSUE TITLE
Status cuma read/delay

### ISSUE THREAD

**Issue by shansekai** [MhankBarBar/whatsapp-bot#23]
![20200930_132109](https://user-images.githubusercontent.com/34540627/94650042-22a4e200-0320-11eb-8dc3-66fe82ab93bd.jpg)

Kenapa kalau udah beberapa jam gitu botnya suka delay gitu? Di ketik !help Statusnya cuma read padahal di log jalan terus..

Sebelumnya terimakasih sudah menyediakan bot ini secara gratis.

**Comment by MhankBarBar** [comment]
Gue juga sering ngalamin kek gini sih wkwk, tapi serius gue gatau permasalahannya dimana

**Comment by shansekai** [comment]
Hmmmm jadi bingung w

**Comment by MhankBarBar** [comment]
Gue pikir cuma gue yang ngalamin:v

**Comment by shansekai** [comment]
Ini juga kalau habis !linkgroup pasti langsung delay bot ny

**Comment by MhankBarBar** [comment]
Kalo emang bikin delay kenapa ga di off-in aja?

**Comment by MFarelSyahtiawan** [comment]
> ![20200930_132109](https://user-images.githubusercontent.com/34540627/94650042-22a4e200-0320-11eb-8dc3-66fe82ab93bd.jpg)
> 
> Kenapa kalau udah beberapa jam gitu botnya suka delay gitu? Di ketik !help Statusnya cuma read padahal di log jalan terus..
> 
> Sebelumnya terimakasih sudah menyediakan bot ini secara gratis.

Solusinya 
ctrl+c 
Y
npm start

Awokwaokwaokwaok:v

**Comment by shansekai** [comment]
> > ![20200930_132109](https://user-images.githubusercontent.com/34540627/94650042-22a4e200-0320-11eb-8dc3-66fe82ab93bd.jpg)
> > Kenapa kalau udah beberapa jam gitu botnya suka delay gitu? Di ketik !help Statusnya cuma read padahal di log jalan terus..
> > Sebelumnya terimakasih sudah menyediakan bot ini secara gratis.
> 
> Solusinya
> ctrl+c
> Y
> npm start
> 
> Awokwaokwaokwaok:v

Oh

**Comment by benirabbny** [comment]
tapi jd ga bisa ninggal
