### ISSUE TITLE
What is the number of my bot?

### ISSUE THREAD

**Issue by urielexis64** [MhankBarBar/whatsapp-bot#231]
I have a doubt about the number of the bot to which I should send the commands.

Can someone help me? Thanks

**Comment by AkirahX** [comment]
You must activate the bot at the number you want, after that use the number at which it was active.

**Comment by AkirahX** [comment]
> I have a doubt about the number of the bot to which I should send the commands.
> 
> Can someone help me? Thanks

You must activate the bot at the number you want, after that use the number at which it was active.

**Comment by urielexis64** [comment]
> > I have a doubt about the number of the bot to which I should send the commands.
> > 
> > Can someone help me? Thanks
> 
> You must activate the bot at the number you want, after that use the number at which it was active.

This number must be from WhatsApp Business?

**Comment by AkirahX** [comment]
> > > I have a doubt about the number of the bot to which I should send the commands.
> > > Can someone help me? Thanks
> > 
> > 
> > You must activate the bot at the number you want, after that use the number at which it was active.
> 
> This number must be from WhatsApp Business?

Not necessarily, I used it on regular Whatsapp and everything worked out
