### ISSUE TITLE
ga bisa konek 

### ISSUE THREAD

**Issue by benirabbny** [MhankBarBar/whatsapp-bot#26]
![image](https://user-images.githubusercontent.com/68042984/94925349-423b3680-04e9-11eb-922f-f4a6c3251272.png)
ini kenapa bro ? kok disuruh scan mulu yak

**Comment by MFarelSyahtiawan** [comment]
> ![image](https://user-images.githubusercontent.com/68042984/94925349-423b3680-04e9-11eb-922f-f4a6c3251272.png)
> ini kenapa bro ? kok disuruh scan mulu yak

Problem Di Koneksi Mu:v

**Comment by benirabbny** [comment]
> > ![image](https://user-images.githubusercontent.com/68042984/94925349-423b3680-04e9-11eb-922f-f4a6c3251272.png)
> > ini kenapa bro ? kok disuruh scan mulu yak
> 
> Problem Di Koneksi Mu:v

oiya fak kirain rdp nya
