### ISSUE TITLE
IG Downloder Error

### ISSUE THREAD

**Issue by aidilaryanto** [MhankBarBar/whatsapp-bot#27]
![Screenshot_20201003-123527490](https://user-images.githubusercontent.com/57789597/94983402-077ee000-0575-11eb-86b8-9d5cf01e7b9a.jpg)

Bang, cara fixnya gimana? Ngirimnya file html

**Comment by MhankBarBar** [comment]
Error di apinya gan, blom saya fix

**Comment by aidilaryanto** [comment]
> Error di apinya gan, blom saya fix

Oke gan. Tiktok downloader gak di add bang?

**Comment by MhankBarBar** [comment]
Hmm tunggu aja gan, mungkin saya tambahin nanti
