### ISSUE TITLE
yt download munculnya html ?

### ISSUE THREAD

**Issue by mcpr259** [MhankBarBar/whatsapp-bot#30]
itu knapa ya a apa api nya emg dari sononya iklan suruh download dlu yak?
muncul html file pas di klik masuk ke y2mate

**Comment by MhankBarBar** [comment]
Semua gitu? Semua link? Saya belum cek soalnya

**Comment by mcpr259** [comment]
> Semua gitu? Semua link? Saya belum cek soalnya

iya bang pas waktu paertama bisa ke sini kesini malah kluar file html
diklik nge link ke y2mate

**Comment by benirabbny** [comment]
same tadi saya juga gitu

**Comment by bl4nk0n** [comment]
engga, ga semua link kok.
