### ISSUE TITLE
Error di command !igstalk sama beberapa command lainnya

### ISSUE THREAD

**Issue by aidilaryanto** [MhankBarBar/whatsapp-bot#33]
![image](https://user-images.githubusercontent.com/57789597/95009675-7b44e980-0656-11eb-86c1-3b75460f59c9.png)

**Comment by MhankBarBar** [comment]
Gada error kok

**Comment by aidilaryanto** [comment]
Wah. Di aku kok error yah. Bahkan stikerpun gabisa

**Comment by MhankBarBar** [comment]
Done fix
