### ISSUE TITLE
ytmp4 Error

### ISSUE THREAD

**Issue by Samuel11022** [MhankBarBar/whatsapp-bot#34]
saya sudah mencoba beberapa link dari youtube dan hasilnya tetap saja error, saat saya pakai ytmp3 bisa berjalan dengan baik, tetapi saat saya pakai ytmp4 malah error, tolong dong bang solusinya.
![ewerr3ed](https://user-images.githubusercontent.com/67886880/95022186-29f02680-0665-11eb-8eb1-5db0b93d00c9.png)

**Comment by MhankBarBar** [comment]
```bash
> npm update
```

**Comment by MhankBarBar** [comment]
Done fix
