### ISSUE TITLE
Req feature

### ISSUE THREAD

**Issue by shansekai** [MhankBarBar/whatsapp-bot#36]
Halo admin, bisakah saya merequest fitur.

Fiturnya itu, kalau misalnya udah pakai command bot 50x maka otomatis nanti ke 51x nya botnya udah gak merespon ke pengguna bot tersebut.

Terima kasih.

**Comment by MhankBarBar** [comment]
Hmm mending pake bot sebelah:v gaminat bikin limiting commands soalnya

Tapi tau deh wkwk

**Comment by ebet12** [comment]
Fitur sapa member left bang

**Comment by shansekai** [comment]
> Hmm mending pake bot sebelah:v gaminat bikin limiting commands soalnya
> 
> Tapi tau deh wkwk

Sebelah yang mana mint?

**Comment by ebet12** [comment]
> > Hmm mending pake bot sebelah:v gaminat bikin limiting commands soalnya
> > 
> > Tapi tau deh wkwk
> 
> Sebelah yang mana mint?

wa-bot.js buatan itzangga

**Comment by shansekai** [comment]
Ouh yang itu

**Comment by ebet12** [comment]
![IMG20201005172956.jpg](https://user-images.githubusercontent.com/69359263/95097043-38b70600-0757-11eb-91dc-4f0aba9c8472.jpg)

Ada yang tau itu bug apaan?

**Comment by restugbk** [comment]
> Halo admin, bisakah saya merequest fitur.
> 
> Fiturnya itu, kalau misalnya udah pakai command bot 50x maka otomatis nanti ke 51x nya botnya udah gak merespon ke pengguna bot tersebut.
> 
> Terima kasih.

Make RFP BOT bro wkwkwk :v

**Comment by restugbk** [comment]
> > Halo admin, bisakah saya merequest fitur.
> > Fiturnya itu, kalau misalnya udah pakai command bot 50x maka otomatis nanti ke 51x nya botnya udah gak merespon ke pengguna bot tersebut.
> > Terima kasih.
> 
> Make RFP BOT bro wkwkwk :v

![image](https://user-images.githubusercontent.com/69737152/95174097-c809fb00-07e3-11eb-96eb-24886ec0e3dd.png)



> > Halo admin, bisakah saya merequest fitur.
> > Fiturnya itu, kalau misalnya udah pakai command bot 50x maka otomatis nanti ke 51x nya botnya udah gak merespon ke pengguna bot tersebut.
> > Terima kasih.
> 
> Make RFP BOT bro wkwkwk :v

![image](https://user-images.githubusercontent.com/69737152/95174115-cf310900-07e3-11eb-89b2-0c99593c4426.png)

kek gitu bro?

**Comment by restugbk** [comment]
> > Halo admin, bisakah saya merequest fitur.
> > Fiturnya itu, kalau misalnya udah pakai command bot 50x maka otomatis nanti ke 51x nya botnya udah gak merespon ke pengguna bot tersebut.
> > Terima kasih.
> 
> Make RFP BOT bro wkwkwk :v

![image](https://user-images.githubusercontent.com/69737152/95174152-dbb56180-07e3-11eb-836d-0e031641e692.png)

Kek gitu bro?

**Comment by Cahyo224** [comment]
> > > Halo admin, bisakah saya merequest fitur.
> > > Fiturnya itu, kalau misalnya udah pakai command bot 50x maka otomatis nanti ke 51x nya botnya udah gak merespon ke pengguna bot tersebut.
> > > Terima kasih.
> > 
> > 
> > Make RFP BOT bro wkwkwk :v
> 
> ![image](https://user-images.githubusercontent.com/69737152/95174152-dbb56180-07e3-11eb-836d-0e031641e692.png)
> 
> Kek gitu bro?

Passwordnya apa euy .RARnya

**Comment by patrick1135** [comment]
> ![IMG20201005172956.jpg](https://user-images.githubusercontent.com/69359263/95097043-38b70600-0757-11eb-91dc-4f0aba9c8472.jpg)
> 
> Ada yang tau itu bug apaan?

yah loe main di gitpot gua juga disitu tapi biar bisa harus fakeroot

**Comment by patrick1135** [comment]
> > ![IMG20201005172956.jpg](https://user-images.githubusercontent.com/69359263/95097043-38b70600-0757-11eb-91dc-4f0aba9c8472.jpg)
> > Ada yang tau itu bug apaan?
> 
> yah loe main di gitpot gua juga disitu tapi biar bisa harus fakeroot

biar pke comander APT/apt-get

**Comment by Samuel11022** [comment]
> > > > Halo admin, bisakah saya merequest fitur.
> > > > Fiturnya itu, kalau misalnya udah pakai command bot 50x maka otomatis nanti ke 51x nya botnya udah gak merespon ke pengguna bot tersebut.
> > > > Terima kasih.
> > > 
> > > 
> > > Make RFP BOT bro wkwkwk :v
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69737152/95174152-dbb56180-07e3-11eb-836d-0e031641e692.png)
> > Kek gitu bro?
> 
> Passwordnya apa euy .RARnya

Harus donasi dulu katanya

**Comment by Cahyo224** [comment]
![Screenshot (196)](https://user-images.githubusercontent.com/70569483/95546713-84093700-0a2b-11eb-9896-c373d2a5aa6d.png)
gua tunggu 5 menit kok Authenticating terus ya

**Comment by Samuel11022** [comment]
> ![Screenshot (196)](https://user-images.githubusercontent.com/70569483/95546713-84093700-0a2b-11eb-9896-c373d2a5aa6d.png)
> gua tunggu 5 menit kok Authenticating terus ya

Sebelumnya apakah pernah bergitu atau baru pertama kali langsung kayak gitu?

**Comment by Cahyo224** [comment]
> > ![Screenshot (196)](https://user-images.githubusercontent.com/70569483/95546713-84093700-0a2b-11eb-9896-c373d2a5aa6d.png)
> > gua tunggu 5 menit kok Authenticating terus ya
> 
> Sebelumnya apakah pernah bergitu atau baru pertama kali langsung kayak gitu?

kagak pernah, Tadi pagi bro mulai kek gitu

**Comment by restugbk** [comment]
> > > > Halo admin, bisakah saya merequest fitur.
> > > > Fiturnya itu, kalau misalnya udah pakai command bot 50x maka otomatis nanti ke 51x nya botnya udah gak merespon ke pengguna bot tersebut.
> > > > Terima kasih.
> > > 
> > > 
> > > Make RFP BOT bro wkwkwk :v
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/69737152/95174152-dbb56180-07e3-11eb-836d-0e031641e692.png)
> > Kek gitu bro?
> 
> Passwordnya apa euy .RARnya

donasi dlu gan

**Comment by restugbk** [comment]
> > > ![Screenshot (196)](https://user-images.githubusercontent.com/70569483/95546713-84093700-0a2b-11eb-9896-c373d2a5aa6d.png)
> > > gua tunggu 5 menit kok Authenticating terus ya
> > 
> > 
> > Sebelumnya apakah pernah bergitu atau baru pertama kali langsung kayak gitu?
> 
> kagak pernah, Tadi pagi bro mulai kek gitu

di ulang ulang aja terus, emang kayaknya dr open wanya.
open wa sering error soalnya, gk jelas wkwkwk

**Comment by Aryasatya12** [comment]
> > > Hmm mending pake bot sebelah:v gaminat bikin limiting commands soalnya
> > > Tapi tau deh wkwk
> > 
> > 
> > Sebelah yang mana mint?
> 
> wa-bot.js buatan itzangga

Ada yang punya sc nya wa-bot.js?

**Comment by Cahyo224** [comment]
> > > > Hmm mending pake bot sebelah:v gaminat bikin limiting commands soalnya
> > > > Tapi tau deh wkwk
> > > 
> > > 
> > > Sebelah yang mana mint?
> > 
> > 
> > wa-bot.js buatan itzangga
> 
> Ada yang punya sc nya wa-bot.js?

ada. Gua
