### ISSUE TITLE
[HELP] [ASK] Why Not Responding in Chat?

### ISSUE THREAD

**Issue by danielraffiando** [MhankBarBar/whatsapp-bot#37]
![Capture](https://user-images.githubusercontent.com/34260317/95112653-68700900-076b-11eb-9738-add788daaf01.PNG)

**Comment by MhankBarBar** [comment]
The state state is pairing, please type CTRL-c then rerun the script

**Comment by danielraffiando** [comment]
> The state is pairing, please type CTRL-c then rerun the script

Tried it 30 times, but it's still like that. is there something wrong in the source code?

**Comment by MhankBarBar** [comment]
Checked whether your network is normal? And have you tried to re-scan the QR code?

**Comment by MhankBarBar** [comment]
Solve? Close
