### ISSUE TITLE
NEW: REQ FEATURES

### ISSUE THREAD

**Issue by bl4nk0n** [MhankBarBar/whatsapp-bot#38]
**hope u want to update this feature :)**

**1. Translate text (quote only)
2. sticker with no background
3. Create Custom meme (top text & bottom text)
4. check data on the spread of Covid-19 in certain locations
5. Check Shipping info (indonesia only)**

_actually i have the script *all of that*. but, i can't update it :( soo... yahh i need ur help as own this sc_ :+1:

**Comment by bl4nk0n** [comment]
> For number 2, it's possible if the image sended as document & png, WA it self didn't support png so i think if the media was not a document you need to remove the background using an API or other things

maybe that can use (remove.bg) API. idk

**Comment by akumund** [comment]
> > For number 2, it's possible if the image sended as document & png, WA it self didn't support png so i think if the media was not a document you need to remove the background using an API or other things
> 
> maybe that can use (remove.bg) API. idk

removebg must paid because free is possible

**Comment by restugbk** [comment]
mampir https://api.i-tech.id/
