### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by idkmew** [MhankBarBar/whatsapp-bot#40]
Hallo min, saya sebagai pengguna BOT anda sangat menghormati tapi saya bingung, BOT bekerja dengan normal tapi hanya beberapa menit saja, setelahnya BOT tersebut seperti tidak aktif, dan status BOTnya hanya read msg tapi tidak meng exec command yg udah diatur seperti !help dan lainnya, apakah bisa membantu saya?

**Comment by MhankBarBar** [comment]
Saya juga bingung sama bug yang satu ini, mungkin dari beberapa user ada yang tau cara fixnya.

**Comment by MhankBarBar** [comment]
Tapi setau saya, kendala terjadi karena terlalu banyak pesan, tapi saya tidak begitu yakin😁

**Comment by idkmew** [comment]
> Tapi setau saya, kendala ini terjadi karena terlalu banyak pesan, tapi saya tidak begitu yakin😁

Apa Bot yang masnya buat pernah mas tes dan tidak ada kendala seperti yang saya alami?

**Comment by MhankBarBar** [comment]
Saya juga pernah mengalami kendala seperti itu, tapi setelah saya batasi jumlah group dan juga chat kendala seperti itu hilang.

Tapi saya tidak begitu yakin.

**Comment by restugbk** [comment]
coba install ulang npmnya

**Comment by restugbk** [comment]
kadang w juga kek gitu, tapi setelah di npm i bisa lagi

**Comment by restugbk** [comment]
> udah saya coba bro saya hapus beberapa folder nodenya dan lainnya yg awalny gaad trus saya npm i dan saya coba npm start ttp aja sama

node_modules apus sama package-lock, trus npm i trus npm start?

**Comment by restugbk** [comment]
bentar dah w mo nanya, ini fs kenapa gk kebaca mulu y?

![image](https://user-images.githubusercontent.com/69737152/95222897-30c49800-0823-11eb-800d-223cfb984c0e.png)

**Comment by MhankBarBar** [comment]
file ```welcome.json``` nya ada di dir lib?

**Comment by idkmew** [comment]
> bentar dah w mo nanya, ini fs kenapa gk kebaca mulu y?
> 
> ![image](https://user-images.githubusercontent.com/69737152/95222897-30c49800-0823-11eb-800d-223cfb984c0e.png)

xixi menurutku kykny ntu gaada yg di load di folder. ../.../lib/welcome.json;

**Comment by restugbk** [comment]
> file `welcome.json` nya ada di dir lib?

iya udah ada

**Comment by restugbk** [comment]
tapi kenapa gitu mulu anjaii

**Comment by idkmew** [comment]
> > udah saya coba bro saya hapus beberapa folder nodenya dan lainnya yg awalny gaad trus saya npm i dan saya coba npm start ttp aja sama
> 
> node_modules apus sama package-lock, trus npm i trus npm start?

klo yg package-lock sih engga aku apus karna udah ada emng dari awal jadi yah selain itu and ttp sama

**Comment by restugbk** [comment]
![image](https://user-images.githubusercontent.com/69737152/95223323-a597d200-0823-11eb-9a14-7f123b04681f.png)

**Comment by restugbk** [comment]
> > > udah saya coba bro saya hapus beberapa folder nodenya dan lainnya yg awalny gaad trus saya npm i dan saya coba npm start ttp aja sama
> > 
> > 
> > node_modules apus sama package-lock, trus npm i trus npm start?
> 
> klo yg package-lock sih engga aku apus karna udah ada emng dari awal jadi yah selain itu and ttp sama

coba ss

**Comment by idkmew** [comment]
> file `welcome.json` nya ada di dir lib?



> Saya juga pernah mengalami kendala seperti itu, tapi setelah saya batasi jumlah group dan juga chat kendala seperti itu hilang.
> 
> Tapi saya tidak begitu yakin.

mas berapa batas Group atau priv msg ?

**Comment by MhankBarBar** [comment]
Kalo ada gabakalan muncul ```no such file or directory```

**Comment by restugbk** [comment]
> Kalo ada gabakalan muncul `no such file or directory`

nah itu di ss ada kan?

**Comment by idkmew** [comment]
> > > > udah saya coba bro saya hapus beberapa folder nodenya dan lainnya yg awalny gaad trus saya npm i dan saya coba npm start ttp aja sama
> > > 
> > > 
> > > node_modules apus sama package-lock, trus npm i trus npm start?
> > 
> > 
> > klo yg package-lock sih engga aku apus karna udah ada emng dari awal jadi yah selain itu and ttp sama
> 
> coba ss

![image](https://user-images.githubusercontent.com/72456125/95223601-5efaa580-082c-11eb-853e-d254c3a270fb.png)

**Comment by idkmew** [comment]
> > mas berapa batas Group atau priv msg ?
> 
> Group max 15 sih, cuma kalo private message sering di clear biar ga jadi sampah

yah saya udah hapusin sih and 5 group tapi ttp sama and klo priv msg sih juga sama sering dihapusin and gaada berubah

**Comment by MhankBarBar** [comment]
../../

**Comment by restugbk** [comment]
> > > > > udah saya coba bro saya hapus beberapa folder nodenya dan lainnya yg awalny gaad trus saya npm i dan saya coba npm start ttp aja sama
> > > > 
> > > > 
> > > > node_modules apus sama package-lock, trus npm i trus npm start?
> > > 
> > > 
> > > klo yg package-lock sih engga aku apus karna udah ada emng dari awal jadi yah selain itu and ttp sama
> > 
> > 
> > coba ss
> 
> ![image](https://user-images.githubusercontent.com/72456125/95223601-5efaa580-082c-11eb-853e-d254c3a270fb.png)

yg package-lock.json apus trus npm i

**Comment by restugbk** [comment]
> ../../ ???

ohh iya dh bisa, w yg salah kawokawok

**Comment by MhankBarBar** [comment]
Gimana solved?

**Comment by MhankBarBar** [comment]
Close
