### ISSUE TITLE
Eror setelah beberapa saat bot berjalan

### ISSUE THREAD

**Issue by agusydk3** [MhankBarBar/whatsapp-bot#45]
Kenapa tiap beberapa jam bot sudah berjalan, bot tidak bisa membalas seperti biasa nya
Dan saya mendapatkan eror di vps saya seperti ini
Seluruh command yang saya gunakan di vps selalu merespon seperti ini
Tapi jika di jalankan ulang itu baik baik saja
Tapi berapa jam kemudian lagi akan mengalami masalah seperti itu lagi

~> [EXEC] 10/10 13:12:13 !snk from Agus DxD
(node:12429) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'includes' of undefined
    at t._0x5562c2 (__puppeteer_evaluation_script__:1:56525)
    at t.value (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:490592)
    at t.value (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:488985)
    at t.value (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:1208421)
    at t.value [as _triggerEvents] (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:490592)
    at t.value [as trigger] (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:488985)
    at t.value [as _set] (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:883202)
    at t.value [as set] (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:882150)
    at t.set (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:380540)
    at Function.assign (<anonymous>)
    at ExecutionContext._evaluateInternal (/root/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/root/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
(node:12429) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 21)

![IMG_20201010_131949](https://user-images.githubusercontent.com/57493908/95647675-95217900-0afb-11eb-9b40-d52f7b5ffacf.jpg)

**Comment by benirabbny** [comment]
sama gan

**Comment by Cahyo224** [comment]
> Kenapa tiap beberapa jam bot sudah berjalan, bot tidak bisa membalas seperti biasa nya
> Dan saya mendapatkan eror di vps saya seperti ini
> Seluruh command yang saya gunakan di vps selalu merespon seperti ini
> Tapi jika di jalankan ulang itu baik baik saja
> Tapi berapa jam kemudian lagi akan mengalami masalah seperti itu lagi
> 
> ~> [EXEC] 10/10 13:12:13 !snk from Agus DxD
> (node:12429) UnhandledPromiseRejectionWarning: Error: Evaluation failed: TypeError: Cannot read property 'includes' of undefined
> at t._0x5562c2 (**puppeteer_evaluation_script**:1:56525)
> at t.value (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:490592)
> at t.value (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:488985)
> at t.value (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:1208421)
> at t.value [as _triggerEvents] (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:490592)
> at t.value [as trigger] (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:488985)
> at t.value [as _set] (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:883202)
> at t.value [as set] (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:882150)
> at t.set (https://web.whatsapp.com/app.be9c3816288f96fd707d.js:1:380540)
> at Function.assign ()
> at ExecutionContext._evaluateInternal (/root/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:217:19)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> at async ExecutionContext.evaluate (/root/whatsapp-bot/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:106:16)
> (node:12429) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 21)
> 
> ![IMG_20201010_131949](https://user-images.githubusercontent.com/57493908/95647675-95217900-0afb-11eb-9b40-d52f7b5ffacf.jpg)

sama njir, Gua juga gitu

**Comment by shansekai** [comment]
W jg gini gak sc bang yoga gak ini sama aja begitu.. tapi lancar lancar aj sih

**Comment by MhankBarBar** [comment]
Wkwk gue gabisa jawab:v

**Comment by MhankBarBar** [comment]
Close.
