### ISSUE TITLE
Sticker not working

### ISSUE THREAD

**Issue by MSI0072** [MhankBarBar/whatsapp-bot#46]
~> [EXEC] 11/10 00:31:15 !stickergif from Fakhri (26)
(node:6731) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './media/output.gif'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at /home/c0d3x/Documents/bot/whatsapp-bot/msgHndlr.js:105:46
    at ChildProcess.exithandler (child_process.js:310:5)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
(node:6731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)

Please help me

**Comment by MhankBarBar** [comment]
```bash
> npm install gify-cli
```

**Comment by aidilaryanto** [comment]
> ~> [EXEC] 11/10 00:31:15 !stickergif from Fakhri (26)
> (node:6731) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './media/output.gif'
> at Object.openSync (fs.js:462:3)
> at Object.readFileSync (fs.js:364:35)
> at /home/c0d3x/Documents/bot/whatsapp-bot/msgHndlr.js:105:46
> at ChildProcess.exithandler (child_process.js:310:5)
> at ChildProcess.emit (events.js:315:20)
> at ChildProcess.EventEmitter.emit (domain.js:483:12)
> at maybeClose (internal/child_process.js:1021:16)
> at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> (node:6731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> 
> Please help me

Ini linux? aku juga gini. udah install gify-cli masih sama

**Comment by bdrsmsdn** [comment]
> > ~> [EXEC] 11/10 00:31:15 !stickergif from Fakhri (26)
> > (node:6731) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open './media/output.gif'
> > at Object.openSync (fs.js:462:3)
> > at Object.readFileSync (fs.js:364:35)
> > at /home/c0d3x/Documents/bot/whatsapp-bot/msgHndlr.js:105:46
> > at ChildProcess.exithandler (child_process.js:310:5)
> > at ChildProcess.emit (events.js:315:20)
> > at ChildProcess.EventEmitter.emit (domain.js:483:12)
> > at maybeClose (internal/child_process.js:1021:16)
> > at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> > (node:6731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
> > Please help me
> 
> this is linux? i'm already installed gify-cli but still error like this

i use windows but i got this error too
