### ISSUE TITLE
Nanya

### ISSUE THREAD

**Issue by idkmew** [MhankBarBar/whatsapp-bot#47]
Permisi kak, mau nanya gmna ya cara ngatasi pas udah di ekstract and dijalankan berhasil dan pas nyoba" untuk nambah fitur jadi aku ubah keseluruhannya and aku coba malah nemu error dan error ny bermasalah klo gasalah di package.json, dan aku coba hapus foldernya dan ekstract ulang dan pas aku jalanin malah Botnya ga berhasil dan aku coba ngejalaninny di 2 media : 1. media cmd 2. media vs code, klo yg cmd malah stuck di Authenticating sedangkan yg di vscode ga terjadi ap" dan stuck seperti di gambar bawah ni :'( ap ad saran mungkin gmna cara ngereset seperti semula agar bisa bekerja BOTny, atau mungkin harus ngehapus folder ap gtu dari FOlder Botny, mohon bantuanny
![image](https://user-images.githubusercontent.com/72456125/95680570-3a784200-0c0d-11eb-8cc2-d873584762ac.png)

**Comment by bl4nk0n** [comment]
> Permisi kak, mau nanya gmna ya cara ngatasi pas udah di ekstract and dijalankan berhasil dan pas nyoba" untuk nambah fitur jadi aku ubah keseluruhannya and aku coba malah nemu error dan error ny bermasalah klo gasalah di package.json, dan aku coba hapus foldernya dan ekstract ulang dan pas aku jalanin malah Botnya ga berhasil dan aku coba ngejalaninny di 2 media : 1. media cmd 2. media vs code, klo yg cmd malah stuck di Authenticating sedangkan yg di vscode ga terjadi ap" dan stuck seperti di gambar bawah ni :'( ap ad saran mungkin gmna cara ngereset seperti semula agar bisa bekerja BOTny, atau mungkin harus ngehapus folder ap gtu dari FOlder Botny, mohon bantuanny
> ![image](https://user-images.githubusercontent.com/72456125/95680570-3a784200-0c0d-11eb-8cc2-d873584762ac.png)

coba aja re install
