### ISSUE TITLE
Fitur bc

### ISSUE THREAD

**Issue by Johanes123** [MhankBarBar/whatsapp-bot#5]
Fitur bc kok ga bisa bang?
Atau aku salah penggunaan?
Kasih tau dong

**Comment by MhankBarBar** [comment]
Gabisa gimana gan?

**Comment by nikkixploit** [comment]
> Fitur bc kok ga bisa bang?
> Atau aku salah penggunaan?
> Kasih tau dong

Dibagian link [Ini](https://github.com/MhankBarBar/whatsapp-bot/blob/ea8ce44dfc78d6155d3e596dff76821f8ed4f3eb/msgHndlr.js#L40) udah diubah belum bang?

**Comment by MhankBarBar** [comment]
> > Fitur bc kok ga bisa bang?
> > Atau aku salah penggunaan?
> > Kasih tau dong
> 
> Dibagian line [Ini](https://github.com/MhankBarBar/whatsapp-bot/blob/ea8ce44dfc78d6155d3e596dff76821f8ed4f3eb/msgHndlr.js#L40) udah diubah belum bang?

Yapz di bagian itu kudu di set dulu emang, kalo ga di set ya gabisa wkwk

**Comment by Johanes123** [comment]
> 
> 
> > Fitur bc kok ga bisa bang?
> > Atau aku salah penggunaan?
> > Kasih tau dong
> 
> Dibagian line [Ini](https://github.com/MhankBarBar/whatsapp-bot/blob/ea8ce44dfc78d6155d3e596dff76821f8ed4f3eb/msgHndlr.js#L40) udah diubah belum bang?

089555179923@c.us gitu?

**Comment by MhankBarBar** [comment]
`62895xxxxx@c.us` format nomor di awali 62

**Comment by Johanes123** [comment]
> 
> 
> `62895xxxxx@c.us` format nomor di awali 62
> 
> Example:
> 
> ```js
> const isOwner = sender.id === '6285892766102@c.us'
> ```

stiker no bg itu sama giphy ga bisa di gunain ya bang?

**Comment by MhankBarBar** [comment]
> stiker no bg itu sama giphy ga bisa di gunain ya bang?

Blom bisa gan

**Comment by Johanes123** [comment]
cara gunain nya gimana bang
udah aku ketik #bc anjay, tapi ga keluar kalo di msgHandler nya dah ku ubah nomor nya juga
apa aku yang salah cara penggunaan nya?
aku ketik di chat kontak ngasal

**Comment by MhankBarBar** [comment]
Prefix nya ! Gan bukan #

Pada tanggal Kam, 17 Sep 2020 06.01, Johanes123 <notifications@github.com>
menulis:

**Comment by MhankBarBar** [comment]
Ketik `!bc Teks` bukan `#bc Teks`

**Comment by Johanes123** [comment]
> 
> 
> Ketik `!bc Teks` bukan `#bc Teks`

prefix nya ku ganti jadi #

**Comment by Johanes123** [comment]
gunain nya di chat atau gimana?

**Comment by Johanes123** [comment]
tadi aku gunain di chat (random)

**Comment by Johanes123** [comment]
lah anjay ga di bales :"v

**Comment by nikkixploit** [comment]
> tadi aku gunain di chat (random)

Gunainnya di nomor whatsapp yang kamu masukin di lini ini : 
const isOwner = sender.id === '6285892766102@c.us'

**Comment by Johanes123** [comment]
> 
> 
> > tadi aku gunain di chat (random)
> 
> Gunainnya di nomor whatsapp yang kamu masukin di lini ini :
> const isOwner = sender.id === '[6285892766102@c.us](mailto:6285892766102@c.us)'

oke tq work bang
