### ISSUE TITLE
Command Mode  

### ISSUE THREAD

**Issue by reactmore** [MhankBarBar/whatsapp-bot#50]
Saya gk tau namanya , jadi kalo kita masuk ke 1 command kalo belum di stop command lain gk fungsi itu gimana ya gan

**Comment by MhankBarBar** [comment]
Mksdnya gimana gan? Gue ga ngerti pertanyaan lu:v

**Comment by reactmore** [comment]
> Mksdnya gimana gan? Gue ga ngerti pertanyaan lu:v

ke gini gan https://streamable.com/vrzzoy

**Comment by reactmore** [comment]
Update udah bisa ternyata nama methodnya nested switch case heheh sorry
