### ISSUE TITLE
Clear all Chat Bot Leave sendiri

### ISSUE THREAD

**Issue by agusydk3** [MhankBarBar/whatsapp-bot#52]
Sob napa ya
Abis ane !clearall bot nya leave sendiri kadang dr gtub
Member padahal 60an

![IMG_20201013_090209](https://user-images.githubusercontent.com/57493908/95806871-fbdca780-0d32-11eb-8ddf-fb10344543c8.jpg)

**Comment by MRHRTZ** [comment]
> Sob napa ya
> Abis ane !clearall bot nya leave sendiri kadang dr gtub
> Member padahal 60an
> 
> ![IMG_20201013_090209](https://user-images.githubusercontent.com/57493908/95806871-fbdca780-0d32-11eb-8ddf-fb10344543c8.jpg)

Coba liat case code yg !clearallnya

**Comment by ijmalan** [comment]
> > Sob napa ya
> > Abis ane !clearall bot nya leave sendiri kadang dr gtub
> > Member padahal 60an
> > ![IMG_20201013_090209](https://user-images.githubusercontent.com/57493908/95806871-fbdca780-0d32-11eb-8ddf-fb10344543c8.jpg)
> 
> Coba liat case code yg !clearallnya

Punten Suhu
