### ISSUE TITLE
IG FB YT gk bisa di pake

### ISSUE THREAD

**Issue by hidagans** [MhankBarBar/whatsapp-bot#53]
error 404 not found terus bang

**Comment by MSI0072** [comment]
> error 404 not found terus bang

![image](https://user-images.githubusercontent.com/63404067/95821253-cd22f900-0d53-11eb-88a6-3b1d9bb0294c.png)

di gw bisa 
coba install ulang

**Comment by MSI0072** [comment]
> error 404 not found terus bang

kalo masi ga bisa coba dari sini https://github.com/ArugaZ/whatsapp-bot-1/tree/patch-1

**Comment by hidagans** [comment]
Pada tanggal Sel, 13 Okt 2020 12.59 PM, MSI0072 <notifications@github.com>
menulis:

**Comment by hidagans** [comment]
IG & FB gbisa

Pada tanggal Sel, 13 Okt 2020 12.59 PM, MSI0072 <notifications@github.com>
menulis:
