### ISSUE TITLE
RandomAnime Eror

### ISSUE THREAD

**Issue by agusydk3** [MhankBarBar/whatsapp-bot#57]
![image](https://user-images.githubusercontent.com/57493908/96131554-897ee980-0f23-11eb-8a2e-671b668f2836.png)
[ERROR] Error: unexpected response Service Temporarily Unavailable
    at randomNimek (/root/whatsapp-bot/lib/functions.js:94:34)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

knapa itu om

**Comment by agusydk3** [comment]
njir di vps tmn w bisa
vps w napa ga bisa :V

**Comment by shansekai** [comment]
> ![image](https://user-images.githubusercontent.com/57493908/96131554-897ee980-0f23-11eb-8a2e-671b668f2836.png)
> [ERROR] Error: unexpected response Service Temporarily Unavailable
> at randomNimek (/root/whatsapp-bot/lib/functions.js:94:34)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 
> knapa itu om

Dari webnya sob api.computerfreaker.cf/v1/anime

**Comment by agusydk3** [comment]
> > ![image](https://user-images.githubusercontent.com/57493908/96131554-897ee980-0f23-11eb-8a2e-671b668f2836.png)
> > [ERROR] Error: unexpected response Service Temporarily Unavailable
> > at randomNimek (/root/whatsapp-bot/lib/functions.js:94:34)
> > at runMicrotasks ()
> > at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > knapa itu om
> 
> Dari webnya sob https://api.computerfreaker.cf/v1/anime

we

> > ![image](https://user-images.githubusercontent.com/57493908/96131554-897ee980-0f23-11eb-8a2e-671b668f2836.png)
> > [ERROR] Error: unexpected response Service Temporarily Unavailable
> > at randomNimek (/root/whatsapp-bot/lib/functions.js:94:34)
> > at runMicrotasks ()
> > at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > knapa itu om
> 
> Dari webnya sob https://api.computerfreaker.cf/v1/anime

bot temen ku makek sc mhankbarbar bisa tapi sob

**Comment by agusydk3** [comment]
> > ![image](https://user-images.githubusercontent.com/57493908/96131554-897ee980-0f23-11eb-8a2e-671b668f2836.png)
> > [ERROR] Error: unexpected response Service Temporarily Unavailable
> > at randomNimek (/root/whatsapp-bot/lib/functions.js:94:34)
> > at runMicrotasks ()
> > at processTicksAndRejections (internal/process/task_queues.js:97:5)
> > knapa itu om
> 
> Dari webnya sob https://api.computerfreaker.cf/v1/anime

bot temen ku makek sc mhankbarbar juga bisa sob random anime nya
punya ku eror
