### ISSUE TITLE
FIX FOR LISTDAERAH

### ISSUE THREAD

**Issue by MFarelSyahtiawan** [MhankBarBar/whatsapp-bot#64]
This Code For Fix !listDaerah For !jadwalShalat

In msgHndlr.js
```javascript
const { help, snk, info, donate, readme, listChannel, listDaerah } require=('./lib/help')
.
.
        case '!listDaerah':
            client.reply(from, listDaerah, id)
            break
```
In help.js
```javascript
function listDaerah() {
    return 'List Daerah yang tersedia : Ambarawa, Ambon, Amlapura, Amuntai, Argamakmur, Atambua, Babo, Bagan Siapiapi, Kalteng, Bajawa, Balige, Balikpapan, Banda Aceh, Bandarlampung, Bandung, Bangkalan, Bangkinang, Bangko, Bangli, Banjar, Banjar Baru, Banjarmasin, Banjarnegara, Bantaeng, Banten, Bantul, Banyuwangi, Barabai, Barito, Barru, Batam, Batang, Batu, Baturaja, Batusangkar, Baubau, Bekasi, Bengkalis, Bengkulu, Benteng, Biak, Bima, Binjai, Bireuen, Bitung, Blitar, Blora, Bogor, Bojonegoro, Bondowoso, Bontang, Boyolali, Brebes, Bukit Tinggi, Maluku, Bulukumba, Buntok, Cepu, Ciamis, Cianjur, Cibinong, Cilacap, Cilegon, Cimahi, Cirebon, Curup, Demak, Denpasar, Depok, Dili, Dompu, Donggala, Dumai, Ende, Enggano, Enrekang, Fakfak, Garut, Gianyar, Gombong, Gorontalo, Gresik, Gunung Sitoli, Indramayu, Jakarta Barat, Jakarta Pusat, Jakarta Selatan, Jakarta Timur, Jakarta Utara, Jambi, Jayapura, Jember, Jeneponto, Jepara, Jombang, Kabanjahe, Kalabahi, Kalianda, Kandangan, Karanganyar, Karawang, Kasungan, Kayuagung, Kebumen, Kediri, Kefamenanu, Kendal, Kendari, Kertosono, Ketapang, Kisaran, Klaten, Kolaka, Kota Baru Pulau Laut, Kota Bumi, Kota Jantho, Kotamobagu, Kuala Kapuas, Kuala Kurun, Kuala Pembuang, Kuala Tungkal, Kudus, Kuningan, Kupang, Kutacane, Kutoarjo, Labuhan, Lahat, Lamongan, Langsa, Larantuka, Lawang, Lhoseumawe, Limboto, Lubuk Basung, Lubuk Linggau, Lubuk Pakam, Lubuk Sikaping, Lumajang, Luwuk, Madiun, Magelang, Magetan, Majalengka, Majene, Makale, Makassar, Malang, Mamuju, Manna, Manokwari, Marabahan, Maros, Martapura Kalsel, Sulsel, Masohi, Mataram, Maumere, Medan, Mempawah, Menado, Mentok, Merauke, Metro, Meulaboh, Mojokerto, Muara Bulian, Muara Bungo, Muara Enim, Muara Teweh, Muaro Sijunjung, Muntilan, Nabire, Negara, Nganjuk, Ngawi, Nunukan, Pacitan, Padang, Padang Panjang, Padang Sidempuan, Pagaralam, Painan, Palangkaraya, Palembang, Palopo, Palu, Pamekasan, Pandeglang, Pangka_, Pangkajene Sidenreng, Pangkalan Bun, Pangkalpinang, Panyabungan, Par_, Parepare, Pariaman, Pasuruan, Pati, Payakumbuh, Pekalongan, Pekan Baru, Pemalang, Pematangsiantar, Pendopo, Pinrang, Pleihari, Polewali, Pondok Gede, Ponorogo, Pontianak, Poso, Prabumulih, Praya, Probolinggo, Purbalingga, Purukcahu, Purwakarta, Purwodadigrobogan, Purwokerto, Purworejo, Putussibau, Raha, Rangkasbitung, Rantau, Rantauprapat, Rantepao, Rembang, Rengat, Ruteng, Sabang, Salatiga, Samarinda, Kalbar, Sampang, Sampit, Sanggau, Sawahlunto, Sekayu, Selong, Semarang, Sengkang, Serang, Serui, Sibolga, Sidikalang, Sidoarjo, Sigli, Singaparna, Singaraja, Singkawang, Sinjai, Sintang, Situbondo, Slawi, Sleman, Soasiu, Soe, Solo, Solok, Soreang, Sorong, Sragen, Stabat, Subang, Sukabumi, Sukoharjo, Sumbawa Besar, Sumedang, Sumenep, Sungai Liat, Sungai Penuh, Sungguminasa, Surabaya, Surakarta, Tabanan, Tahuna, Takalar, Takengon, Tamiang Layang, Tanah Grogot, Tangerang, Tanjung Balai, Tanjung Enim, Tanjung Pandan, Tanjung Pinang, Tanjung Redep, Tanjung Selor, Tapak Tuan, Tarakan, Tarutung, Tasikmalaya, Tebing Tinggi, Tegal, Temanggung, Tembilahan, Tenggarong, Ternate, Tolitoli, Tondano, Trenggalek, Tual, Tuban, Tulung Agung, Ujung Berung, Ungaran, Waikabubak, Waingapu, Wamena, Watampone, Watansoppeng, Wates, Wonogiri, Wonosari, Wonosobo, Yogyakarta'
}
exports.listDaerah = listDaerah() 
```

CATATAN :

- KAGA PAKE API 🔥 LAGI
KETIK MANUAL. 

- UNTUK DAERAH "PAPANGO" GANTI JADI "PAPANGGO" (×2G) 

Terima Kasih

**Comment by MFarelSyahtiawan** [comment]
=========================
TUTOR PULL REQUEST?? 
Biar w taro ini di Pull Request
=========================

**Comment by Cahyo224** [comment]
> This Code For Fix !listDaerah For !jadwalShalat
> 
> In msgHndlr.js
> 
> ```js
> const { help, snk, info, donate, readme, listChannel, listDaerah } require=('./lib/help')
> .
> .
>         case '!listDaerah':
>             client.reply(from, listDaerah, id)
>             break
> ```
> 
> In help.js
> 
> ```js
> function listDaerah() {
>     return 'List Daerah yang tersedia : Ambarawa, Ambon, Amlapura, Amuntai, Argamakmur, Atambua, Babo, Bagan Siapiapi, Kalteng, Bajawa, Balige, Balikpapan, Banda Aceh, Bandarlampung, Bandung, Bangkalan, Bangkinang, Bangko, Bangli, Banjar, Banjar Baru, Banjarmasin, Banjarnegara, Bantaeng, Banten, Bantul, Banyuwangi, Barabai, Barito, Barru, Batam, Batang, Batu, Baturaja, Batusangkar, Baubau, Bekasi, Bengkalis, Bengkulu, Benteng, Biak, Bima, Binjai, Bireuen, Bitung, Blitar, Blora, Bogor, Bojonegoro, Bondowoso, Bontang, Boyolali, Brebes, Bukit Tinggi, Maluku, Bulukumba, Buntok, Cepu, Ciamis, Cianjur, Cibinong, Cilacap, Cilegon, Cimahi, Cirebon, Curup, Demak, Denpasar, Depok, Dili, Dompu, Donggala, Dumai, Ende, Enggano, Enrekang, Fakfak, Garut, Gianyar, Gombong, Gorontalo, Gresik, Gunung Sitoli, Indramayu, Jakarta Barat, Jakarta Pusat, Jakarta Selatan, Jakarta Timur, Jakarta Utara, Jambi, Jayapura, Jember, Jeneponto, Jepara, Jombang, Kabanjahe, Kalabahi, Kalianda, Kandangan, Karanganyar, Karawang, Kasungan, Kayuagung, Kebumen, Kediri, Kefamenanu, Kendal, Kendari, Kertosono, Ketapang, Kisaran, Klaten, Kolaka, Kota Baru Pulau Laut, Kota Bumi, Kota Jantho, Kotamobagu, Kuala Kapuas, Kuala Kurun, Kuala Pembuang, Kuala Tungkal, Kudus, Kuningan, Kupang, Kutacane, Kutoarjo, Labuhan, Lahat, Lamongan, Langsa, Larantuka, Lawang, Lhoseumawe, Limboto, Lubuk Basung, Lubuk Linggau, Lubuk Pakam, Lubuk Sikaping, Lumajang, Luwuk, Madiun, Magelang, Magetan, Majalengka, Majene, Makale, Makassar, Malang, Mamuju, Manna, Manokwari, Marabahan, Maros, Martapura Kalsel, Sulsel, Masohi, Mataram, Maumere, Medan, Mempawah, Menado, Mentok, Merauke, Metro, Meulaboh, Mojokerto, Muara Bulian, Muara Bungo, Muara Enim, Muara Teweh, Muaro Sijunjung, Muntilan, Nabire, Negara, Nganjuk, Ngawi, Nunukan, Pacitan, Padang, Padang Panjang, Padang Sidempuan, Pagaralam, Painan, Palangkaraya, Palembang, Palopo, Palu, Pamekasan, Pandeglang, Pangka_, Pangkajene Sidenreng, Pangkalan Bun, Pangkalpinang, Panyabungan, Par_, Parepare, Pariaman, Pasuruan, Pati, Payakumbuh, Pekalongan, Pekan Baru, Pemalang, Pematangsiantar, Pendopo, Pinrang, Pleihari, Polewali, Pondok Gede, Ponorogo, Pontianak, Poso, Prabumulih, Praya, Probolinggo, Purbalingga, Purukcahu, Purwakarta, Purwodadigrobogan, Purwokerto, Purworejo, Putussibau, Raha, Rangkasbitung, Rantau, Rantauprapat, Rantepao, Rembang, Rengat, Ruteng, Sabang, Salatiga, Samarinda, Kalbar, Sampang, Sampit, Sanggau, Sawahlunto, Sekayu, Selong, Semarang, Sengkang, Serang, Serui, Sibolga, Sidikalang, Sidoarjo, Sigli, Singaparna, Singaraja, Singkawang, Sinjai, Sintang, Situbondo, Slawi, Sleman, Soasiu, Soe, Solo, Solok, Soreang, Sorong, Sragen, Stabat, Subang, Sukabumi, Sukoharjo, Sumbawa Besar, Sumedang, Sumenep, Sungai Liat, Sungai Penuh, Sungguminasa, Surabaya, Surakarta, Tabanan, Tahuna, Takalar, Takengon, Tamiang Layang, Tanah Grogot, Tangerang, Tanjung Balai, Tanjung Enim, Tanjung Pandan, Tanjung Pinang, Tanjung Redep, Tanjung Selor, Tapak Tuan, Tarakan, Tarutung, Tasikmalaya, Tebing Tinggi, Tegal, Temanggung, Tembilahan, Tenggarong, Ternate, Tolitoli, Tondano, Trenggalek, Tual, Tuban, Tulung Agung, Ujung Berung, Ungaran, Waikabubak, Waingapu, Wamena, Watampone, Watansoppeng, Wates, Wonogiri, Wonosari, Wonosobo, Yogyakarta'
> }
> exports.listDaerah = listDaerah() 
> ```
> 
> CATATAN :
> 
> * KAGA PAKE API 🔥 LAGI
>   KETIK MANUAL.
> * UNTUK DAERAH "PAPANGO" GANTI JADI "PAPANGGO" (×2G)
> 
> Terima Kasih

good bro

**Comment by restugbk** [comment]
pake api dr sini aja bro https://api.i-tech.id/

fiturenya bisa di cek dan pasti fix smua

**Comment by MFarelSyahtiawan** [comment]
> pake api dr sini aja bro https://api.i-tech.id/
> 
> fiturenya bisa di cek dan pasti fix smua

Jangan APInya Doang SCnya Kesiniin Lah Awokwaokwaokwaok
Neh 
wa.me/6281219087237

**Comment by restugbk** [comment]
> > pake api dr sini aja bro https://api.i-tech.id/
> > fiturenya bisa di cek dan pasti fix smua
> 
> Jangan APInya Doang SCnya Kesiniin Lah Awokwaokwaokwaok
> Neh
> wa.me/6281219087237

angkut 1jt gw kirim skrng

**Comment by restugbk** [comment]
belajar menghargai karya orang lain bro, jangan cuma nyomot trus di sebar luaskan lagi.
udh make sc orang gratisan trus segala minta donasi donasi kontol

**Comment by MhankBarBar** [comment]
Bjirr ngegas:v

**Comment by MhankBarBar** [comment]
Tadi gue cek apinya, gue liat kek ada beberapa kesamaan sama api [ini](https://mhankbarbar.herokuapp.com/api), tapi keren sih 👍

**Comment by restugbk** [comment]
> Tadi gue cek apinya, gue liat kek ada beberapa kesamaan sama api [ini](https://mhankbarbar.herokuapp.com/api), tapi keren sih 👍

iya sama lu kan cuma copas dr sini https://api.haipbis.xyz/

**Comment by restugbk** [comment]
sama juga fitur w gada yg ngambil dr lu. w juga bisa scrapping kawoawkoawk

**Comment by restugbk** [comment]
langsung di close kwaoakwok

**Comment by MhankBarBar** [comment]
https://github.com/MhankBarBar/MhankBarBar-Api

Ini copas gan?

**Comment by restugbk** [comment]
sisanya?

**Comment by MhankBarBar** [comment]
Gue cuma ambil htmlnya ga lebih, api nya gue ngoding dari 0 Pake python

**Comment by restugbk** [comment]
oke siap bang jago. tapi tetep lengkapan di gw kawoawkok
btw kasian sama scnya yoga. fitur premi dia jadi gk laku gara2 di gratisin kawoakoawkok

**Comment by restugbk** [comment]
belajar menghargai karya orang lain bro kwkwk

**Comment by MhankBarBar** [comment]
Lah situ yang jago, Dahlah ngerry emang kalo debat sama jagoan

**Comment by restugbk** [comment]
awkoakwoawk ampun bang jago
