### ISSUE TITLE
Bot Nulis Error

### ISSUE THREAD

**Issue by CE-10** [MhankBarBar/whatsapp-bot#65]
Pas Ada orang yang ngetik !nulis CONTOH , yang keluar bukannya tulisan CONTOH di kertas melainkan kertas seperti gambar di bawah ini :( 

![after](https://user-images.githubusercontent.com/73124438/96470189-3923c680-1258-11eb-9116-5b0532d5dcea.jpg)

**Comment by MFarelSyahtiawan** [comment]
> Pas Ada orang yang ngetik !nulis CONTOH , yang keluar bukannya tulisan CONTOH di kertas melainkan kertas seperti gambar di bawah ini :(
> 
> ![after](https://user-images.githubusercontent.com/73124438/96470189-3923c680-1258-11eb-9116-5b0532d5dcea.jpg)

Cek Di #17 Ama Di #67
