### ISSUE TITLE
1 TIPS FOR FIX NULIS

### ISSUE THREAD

**Issue by MFarelSyahtiawan** [MhankBarBar/whatsapp-bot#67]
Kalo Ketik  !nulis <teks> ntar hasilnya kan seperti ini 
======================================
![96470189-3923c680-1258-11eb-9116-5b0532d5dcea](https://user-images.githubusercontent.com/58540890/96523151-300a1800-129f-11eb-8f8e-44cc41158351.jpg)

Nah, Cara Fixnya :
===============
1. Buka Folder Botnya
2. ./media/img/
3. Hapus Gambar Yang Namanya "after"

Sekian Terima Kasih

**Comment by CE-10** [comment]
makasih bang :)

**Comment by CE-10** [comment]
Ga work bang, Yang keluar malah kertas kosong tanpa tulisan

**Comment by MhankBarBar** [comment]
> Ga work bang, Yang keluar malah kertas kosong tanpa tulisan

Coba cek [disini](https://github.com/MhankBarBar/whatsapp-bot/issues/17)

**Comment by bdrsmsdn** [comment]
> > Ga work bang, Yang keluar malah kertas kosong tanpa tulisan
> 
> Coba cek [disini](https://github.com/MhankBarBar/whatsapp-bot/issues/17)

gua yg jadi masalah font nya beda :""

**Comment by MFarelSyahtiawan** [comment]
> > Ga work bang, Yang keluar malah kertas kosong tanpa tulisan
> 
> Coba cek [disini](https://github.com/MhankBarBar/whatsapp-bot/issues/17)

Temen Gw Meski Udah Pake Gitu Caranya Tetep Kertas Kosong
Kaga tau gw Mhank cara fixnya

**Comment by MFarelSyahtiawan** [comment]
> > > Ga work bang, Yang keluar malah kertas kosong tanpa tulisan
> > 
> > 
> > Coba cek [disini](https://github.com/MhankBarBar/whatsapp-bot/issues/17)
> 
> gua yg jadi masalah font nya beda :""

Kaga support Win10 kayanya

Hanya beberapa

**Comment by bdrsmsdn** [comment]
> > > > Ga work bang, Yang keluar malah kertas kosong tanpa tulisan
> > > 
> > > 
> > > Coba cek [disini](https://github.com/MhankBarBar/whatsapp-bot/issues/17)
> > 
> > 
> > gua yg jadi masalah font nya beda :""
> 
> Kaga support Win10 kayanya
> 
> Hanya beberapa

oh terus suka melebew jauh melewati buku si tulisannya aokwow

**Comment by MFarelSyahtiawan** [comment]
> > > > > Ga work bang, Yang keluar malah kertas kosong tanpa tulisan
> > > > 
> > > > 
> > > > Coba cek [disini](https://github.com/MhankBarBar/whatsapp-bot/issues/17)
> > > 
> > > 
> > > gua yg jadi masalah font nya beda :""
> > 
> > 
> > Kaga support Win10 kayanya
> > Hanya beberapa
> 
> oh terus suka melebew jauh melewati buku si tulisannya aokwow

Maklum, Namanya Juga Kaga Pake AI Awokwaokwaokwaok 
Coba Req SC Nulis Ke @bintang73

**Comment by CE-10** [comment]
:v udah tak coba masih aja kosong
