### ISSUE TITLE
BUAT YANG STUCK DI AUTHENTICING

### ISSUE THREAD

**Issue by MFarelSyahtiawan** [MhankBarBar/whatsapp-bot#68]
Tips :
=======
Buka Folder Botnya

Hapus Bar².data
Hapus package-lock.js

Run Terminal
npm i
npm install gify-cli -g
npm update
npm start

Scan Ulang QR

Sekian
THANK

**Comment by AthallahDzaki** [comment]
Lebih simplenya 

rm barbar.data

node index.js

**Comment by Cahyo224** [comment]
> # Tips :
> Buka Folder Botnya
> 
> Hapus Bar².data
> Hapus package-lock.js
> 
> Run Terminal
> npm i
> npm install gify-cli -g
> npm update
> npm start
> 
> Scan Ulang QR
> 
> Sekian
> THANK

kagak usah npm i, hapus barbar.data.json, terus scan lagi dah kelar

**Comment by MhankBarBar** [comment]
Close, thanks buat tipsnya gan

**Comment by MFarelSyahtiawan** [comment]
> Close, thanks buat tipsnya gan

🐑 


🐑 = Sheep = Sip
