### ISSUE TITLE
AsK

### ISSUE THREAD

**Issue by bagusdwip** [MhankBarBar/whatsapp-bot#69]
Fiture brainly error kah ? Jawabanya ga ke push/kirim

**Comment by harispoppylatip** [comment]
Iya ak juga error

**Comment by SlavyanDesu** [comment]
Saya error kalau di RDP, kalau di PC nggak

**Comment by SlavyanDesu** [comment]
forEach nya jadi undefined gw bruh

**Comment by harispoppylatip** [comment]
Gua dua duanya

**Comment by restugbk** [comment]
pake api dr sini aja bro https://api.i-tech.id/

fiturenya bisa di cek dan pasti fix smua

**Comment by MhankBarBar** [comment]
Ohh nanti saya fix gan, untuk sekarang di close dulu
