### ISSUE TITLE
How to fix brainly "undefined" ?

### ISSUE THREAD

**Issue by hanesaki** [MhankBarBar/whatsapp-bot#7]
Screenshot

![20200920_121826](https://user-images.githubusercontent.com/43001614/93694913-b2d27280-fb3b-11ea-85a2-f106676e2e67.jpg)

**Comment by MhankBarBar** [comment]
Temen saya juga gini gan, itu emang dah di module <b>brainly-scraper</b> Ntah kenapa result statusnya error 403

**Comment by RaphielHS** [comment]
does the message includes question?
If yes, maybe take a look at ./lib/brainly.js on a code viewer (Sublime text 3 or Visual Studio Code)
there should be *BrainlySearch = (pertanyaan, jumlah, cb)*

Note:
Pertanyaan = Question
Jumlah = amount
cb = ?

**Comment by MhankBarBar** [comment]
cb = result

**Comment by RaphielHS** [comment]
owh
