### ISSUE TITLE
Error pada saat exec command !nulis

### ISSUE THREAD

**Issue by Woogiesii** [MhankBarBar/whatsapp-bot#70]
![image](https://user-images.githubusercontent.com/70749185/96712956-16192400-13ca-11eb-9938-e8d123decc9a.png)

**Comment by Woogiesii** [comment]
![image](https://user-images.githubusercontent.com/70749185/96826549-c71cce80-145d-11eb-82a4-4c9d1c97565b.png)
tambahan error

**Comment by restugbk** [comment]
pake api dr sini aja bro https://api.i-tech.id/

fiturenya bisa di cek dan pasti fix smua

**Comment by rebahanelite** [comment]
> pake api dr sini aja bro https://api.i-tech.id/
> 
> fiturenya bisa di cek dan pasti fix smua

anjay jadi promosi 🤣

**Comment by restugbk** [comment]
yoi

**Comment by harispoppylatip** [comment]
> pake api dr sini aja bro https://api.i-tech.id/
> 
> fiturenya bisa di cek dan pasti fix smua

Tinggal salin aja?

**Comment by restugbk** [comment]
> > pake api dr sini aja bro https://api.i-tech.id/
> > fiturenya bisa di cek dan pasti fix smua
> 
> Tinggal salin aja?

iya tinggal lu arahin apinya lah
