### ISSUE TITLE
kadang bot nya gk ngerespon

### ISSUE THREAD

**Issue by peraaxdd** [MhankBarBar/whatsapp-bot#77]
kadang bot nya gk ngerespon

**Comment by MFarelSyahtiawan** [comment]
> kadang bot nya gk ngerespon

ctrl+c
y
npm start

:v

**Comment by ItzTobz** [comment]
Penyebabnya dari command #linkgroup

**Comment by peraaxdd** [comment]
> Penyebabnya dari command #linkgroup

Sama aja
