### ISSUE TITLE
2 Fitur Error Ditemukan Bang! , Baru² Ini! 

### ISSUE THREAD

**Issue by MFarelSyahtiawan** [MhankBarBar/whatsapp-bot#8]
Yaitu fitur !waifu & Fitur !wallpaper

**Comment by MFarelSyahtiawan** [comment]
Mohon Diperbaiki Secepatnya Yaw Bang!!!

**Comment by MhankBarBar** [comment]
Siap

**Comment by MhankBarBar** [comment]
Untuk waifu bisa di cek di website nya langsung gan `randomwaifu.altervista.org` emang lagi error, dan  wallpaper di next update saya fix
