### ISSUE TITLE
tutor

### ISSUE THREAD

**Issue by natxanss** [MhankBarBar/whatsapp-bot#84]
cara nambah filter gimana ya? misal orang ketik hai ke bot, lalu bot auto bales, trimakasih

**Comment by lokublah** [comment]
> cara nambah filter gimana ya? misal orang ketik hai ke bot, lalu bot auto bales, trimakasih

case 'hai':
client.reply(from, `blablabla`) klo teks mau diksih jrk enter ketik \n

**Comment by ryanpratama-code** [comment]
Kodenya di taruh di file mana pak?

**Comment by benirabbny** [comment]
> Kodenya di taruh di file mana pak?
msghandler

**Comment by andra12lol** [comment]
lGjYt4zA5SQlTDx9z9Ca
