### ISSUE TITLE
weather not working

### ISSUE THREAD

**Issue by chicken999** [MhankBarBar/whatsapp-bot#88]
hi , !weather was working fine until now, it asks me for apikey ,what api should i put in:
const weather = await get.get(`https://mhankbarbar.herokuapp.com/api/cuaca?q=${tempat}&apiKey=${apiKey}`).json()

**Comment by MhankBarBar** [comment]
You can check in [here](https://mhankbarbar.herokuapp.com/api)

**Comment by MhankBarBar** [comment]
Close
