### ISSUE TITLE
mhank kalau ada bacaan apilimit pas lagi igstalk gimana tuh mhank?

### ISSUE THREAD

**Issue by andra12lol** [MhankBarBar/whatsapp-bot#89]

**Comment by MhankBarBar** [comment]
Api limit?

**Comment by BASEBTM** [comment]
> Api limit?
Api is invalid kali. Aku selama pakai belum pernah ada problem apilimit:v

**Comment by MhankBarBar** [comment]
Nah:v

**Comment by usoajwj** [comment]
> Nah:v

Iya mhank maaf ini pake akun yg di android:v

**Comment by MFarelS** [comment]
> Api limit?

IG Stalk Kaga Bisa Dipake Mhank @Cahyo224

**Comment by BASEBTM** [comment]
> >Api limit?
> 
>IG Stalk Kaga Bisa Dipake Mhank @Cahyo224
![IMG_20201027_200739](https://user-images.githubusercontent.com/71388727/97305787-2761a500-1890-11eb-92ce-68929253d1fc.jpg)
aku bisa kok, coba lihat lagi di codingannya

**Comment by andra12lol** [comment]
> > > Api limit?
> > 
> > 
> > IG Stalk Kaga Bisa Dipake Mhank @Cahyo224
> > ![IMG_20201027_200739](https://user-images.githubusercontent.com/71388727/97305787-2761a500-1890-11eb-92ce-68929253d1fc.jpg)
> > aku bisa kok, coba lihat lagi di codingannya

gw codingan dari mhankbarbarnya

**Comment by andra12lol** [comment]
@MhankBarBar gimana mhank?

**Comment by MhankBarBar** [comment]
> @MhankBarBar gimana mhank?

Udh beli apiKeynya? :v

**Comment by MFarelS** [comment]
> > @MhankBarBar gimana mhank?
> 
> Udh beli apiKeynya? :v

Fork Tembus 100 GiveAway API-KEY!! 
Awokwaokwaokesok
