### ISSUE TITLE
Mhank pas nulis error

### ISSUE THREAD

**Issue by usoajwj** [MhankBarBar/whatsapp-bot#90]
![Screenshot_2020-10-28-07-09-22-479_com whatsapp w4b](https://user-images.githubusercontent.com/60127620/97378353-c4eec000-18f4-11eb-81c3-394a82c06043.png)

**Comment by CE-10** [comment]
text nya kepanjangan mungkin

**Comment by MhankBarBar** [comment]
Hooh, gak ngotak teksnya

**Comment by CE-10** [comment]
> 
> 
> Hooh, gak ngotak teksnya

:v

**Comment by lokublah** [comment]
lu kalo mau nulis panjang panjang gitu lu pake background sendiri,length height atur sndiri. lu mahbuat nugas kali wkwk
