### ISSUE TITLE
!ytmp4 error

### ISSUE THREAD

**Issue by fairyenzy** [MhankBarBar/whatsapp-bot#92]
!ytmp4 nya error bang, aku udah coba uninstall vps, ganti os masih tetap gak bisa
![Screenshot_Pixel_Launcher_20201029-110952](https://user-images.githubusercontent.com/61671678/97524599-a57c9380-19d7-11eb-9236-443109fcbaac.png)
![Screenshot_WhatsApp_20201029-111044](https://user-images.githubusercontent.com/61671678/97524609-aad9de00-19d7-11eb-885f-b14378625317.png)

**Comment by MhankBarBar** [comment]
Di gue bisa loh

**Comment by shansekai** [comment]
> !ytmp4 nya error bang, aku udah coba uninstall vps, ganti os masih tetap gak bisa
> ![Screenshot_Pixel_Launcher_20201029-110952](https://user-images.githubusercontent.com/61671678/97524599-a57c9380-19d7-11eb-9236-443109fcbaac.png)
> ![Screenshot_WhatsApp_20201029-111044](https://user-images.githubusercontent.com/61671678/97524609-aad9de00-19d7-11eb-885f-b14378625317.png)

Open wa versi berapa?

Coba pakai yang versi 2.1.6 aja biar gak error

**Comment by restugbk** [comment]
mampir https://api.i-tech.id/
